### PR TITLE
Bugfix/FOUR-5958: Fix the issue where comments referencing a username would no longer match

### PR DESCRIPTION
**Pull request by agustinbusso**
## Issue & Reproduction Steps
Fix the issue where comments referencing a username would no longer match. Instead of storing the username itself in the comment text we should store a reference to the user’s ID and parse that into a username at runtime.

Please refer to: [FOUR-5759: The Processes should be order alphabeticallyTRIAGE](https://processmaker.atlassian.net/browse/FOUR-5759).

- Add a comment and tag some user i.e. "This is my comment @myUser"
- Go to your database to the comments table and search the comment. In the body column you will see the comment with the username: "This is my comment @myUser"

## Solution
- Added an accessor and mutator to comment model to parse between username and id and keep the users references in comments.

## How to Test
- Add a comment and tag some user i.e. "This is my comment @myUser"
- Go to your database to the comments table and search the comment. In the body column you will see the comment with the user id in mustaches: "This is my comment {{1}}"
- Go to the ui and you should see in the comment the username parsed "This is my comment @myUser"

Run test cases

**Working video**

https://user-images.githubusercontent.com/90727999/164788943-4739e38f-58cd-49ae-8623-a06e46ffede4.mov

## Related Tickets & Packages
- [FOUR-5958](https://processmaker.atlassian.net/browse/FOUR-5958)
- You should install package comments.

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5958-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5958-processmaker.ci.processmaker.net

**Review by danloa — CHANGES_REQUESTED** [review]
This PR is perfect to add some unit tests to validate the correctness of the replace using  different strings

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5958-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5958-processmaker.ci.processmaker.net

**Review by danloa — APPROVED** [review]

**Review by ryancooley — APPROVED** [review]

**Pull request merged**
