### PR TITLE
Add option to use a ProcessMaker screen as a setting component

### PR DESCRIPTION
**Pull request by ryancooley**
## Changes
- Adds the option of using an exported ProcessMaker screen as a setting component
- Used by https://github.com/ProcessMaker/package-auth/pull/9 to add a cron job frequency setting

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3218-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3218-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3218-processmaker.ci.processmaker.net

**Review by danloa — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3218-processmaker.ci.processmaker.net

**Pull request merged**
