### PR TITLE
Create Default Templates

### PR DESCRIPTION
**Pull request by estebangallego**
ticket [FOUR-7770](https://processmaker.atlassian.net/browse/FOUR-7770)

## Issue & Reproduction Steps
As a Project Manager, I want to access templates by default in my environment so that I can get my process live more quickly and see more use cases for how I can build my process

## Solution
- Create seeders for the default templates and default category

## How to Test
- Please rollback to create_process_templates_table. eg: `php artisan migrate:rollback --step=2`
- Run `php artisan migrate`
- Make sure you have all the packages installed
- Click on the designer top menu
- Click on the Templates tab
- Select one of the default templates (Employee Onboarding 2023)
- Run the process and make sure it works as expected
-- To make sure the process is working as expected, please make sure you have the setup the default email server
-- For the last step of the process, Create User Script you may need to follow this steps -> ([Script Task cURL Error](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/2820603905/Error+Knowledge+Base#Script-Task-cURL-Error))
-- The last step of the process is handled by a timer so locally, you may need to run these commands.
-- `php artisan schedule:list`
-- `php artisan schedule:work`
-- `php artisan bpmn:timer`

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

[FOUR-7770]: https://processmaker.atlassian.net/browse/FOUR-7770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci:db:clean
.........

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed Could not open input file: deploy-stm/get-url.php

**Comment by pmkerberos** [comment]
QA server was successfully deployed Could not open input file: deploy-stm/get-url.php

**Comment by pmkerberos** [comment]
QA server was successfully deployed Could not open input file: deploy-stm/get-url.php

**Review by mcraeteisha — APPROVED** [review]
Approved!

**Pull request merged**
