### PR TITLE
feature/FOUR-14002: Designer "Assets" icons default color and hover are not the same as figma

### PR DESCRIPTION
**Pull request by luNunezProcessmaker**
## Issue & Reproduction Steps
**Current**
The text: Lower camel case

The icon needs to use the color

The mouse over style fill: #1572C2;
image-20240201-222648

**Expected**
image-20240201-222708

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-14002

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-13fac0e9ed.engk8s.processmaker.net

**Comment by pmPaulis** [comment]
@luNunezProcessmaker 
I have the following observations

1. the letters needs to user the following cs 
```
color: #5E6469;
font-family: "Open Sans";
font-size: 14px;
font-style: normal;
font-weight: 400;
line-height: normal;
letter-spacing: -0.28px;
```
3. The styles for the effects` New and View` are not the same in figma
image
image

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-13fac0e9ed.engk8s.processmaker.net

**Review by fagubla — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-13fac0e9ed.engk8s.processmaker.net

**Pull request merged**
