### PR TITLE
FOUR-FOUR-14996: The list of scripts/screens does not match the pagination selection option.

### PR DESCRIPTION
**Pull request by estebangallego**
## Description
This pull request addresses an issue in the UI where the pagination display is not consistent with the actual number of items shown in lists within the Asets like Screens, Scripts, etc. 

## Steps to Reproduce
1. Navigate to the Designer.
2. Navigate Scripts, Screens, Environment Variables or Pm Blocks.
3. Make sure that you have more than 10 assets in each Page
4. Observe the pagination behavior at the bottom of the list.

## Current Behavior
The list displays more than the set number of items per page (Is currently set a 15), but the pagination control indicates only 10 items per page, leading to confusion about the total number of entries and navigation issues.

Screenshot 2024-04-15 at 1 08 40 PM

## Expected Behavior
The list should be congruent with the pagination settings. If pagination is set to 10 items per page, only 10 items should be displayed at any given time.

Screenshot 2024-04-15 at 1 09 19 PM

## Changes Made
- Updated `datatable.js` to ensure that the default pagination setting is correctly enforced to display 10 items per page. This change resolves the inconsistency between the number of displayed items and the pagination controls.

## How to Test
- Navigate to any of the Assets and ensure that the pagination correctly shows 10 items per page as intended.
- Verify that navigating through pages displays a consistent and correct number of items.

## Related Tickets & Packages
- Ticket: [FOUR-14996](https://processmaker.atlassian.net/browse/FOUR-14996)
- ci:next
- ci:deploy

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

[FOUR-14996]: https://processmaker.atlassian.net/browse/FOUR-14996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-da585e8abb.engk8s.processmaker.net

**Review by mcraeteisha — APPROVED** [review]
Approved!

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-da585e8abb.engk8s.processmaker.net

**Comment by estebangallego** [comment]
Closing this PR in exchange for this #6683

**Pull request closed without merging**
