### PR TITLE
Allow filtering files by ID

### PR DESCRIPTION
**Pull request by sanjacornelius**
## Issue & Reproduction Steps
Ticket: [FOUR-5191](https://processmaker.atlassian.net/browse/FOUR-5191)

This PR is part of the file download refactor, which adds the ability to filter files by ID and name.

## Related Tickets & Packages

- Screen Builder PR: https://github.com/ProcessMaker/screen-builder/pull/1190
- Files Package PR: https://github.com/ProcessMaker/package-files/pull/70
- Web Entry Package PR - https://github.com/ProcessMaker/package-webentry/pull/136

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5191-4-2-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5191-4-2-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5191-4-2-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5191-4-2-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5191-4-2-processmaker.ci.processmaker.net

**Review by runyan-co — APPROVED** [review]
Tested and approved for 4.2

**Review by ryancooley — APPROVED** [review]

**Pull request merged**
