### PR TITLE
MAUI Demo deployment (DO NOT MERGE THIS PR)

### PR DESCRIPTION
**Pull request by caleeli**
MAUI Demo CI deployment

DO NOT MERGE THIS PR

ci:deploy
ci:next
ci:processmaker:next
ci:screen-builder:next
ci:package-testing:feature/FOUR-8066
ci:connector-send-email:feature/FOUR-10818
ci:package-data-sources:next
ci:package-decision-engine:next
ci:package-files:next
ci:package-vocabularies:next

.........

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-c3a7be96ef.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-c3a7be96ef.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-c3a7be96ef.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-c3a7be96ef.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-c3a7be96ef.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-c3a7be96ef.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-c3a7be96ef.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-c3a7be96ef.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-c3a7be96ef.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-c3a7be96ef.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-c3a7be96ef.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-c3a7be96ef.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-c3a7be96ef.eng.processmaker.net

**Comment by caleeli** [comment]
Tests and merge completed. This testing PR is closed.

**Pull request closed without merging**
