### PR TITLE
4.1 to 4.2 batch 4

### PR DESCRIPTION
**Pull request by nolanpro**
Contains the following fixes:

Ticket # | Link
-- | --
198 | http://tickets.pm4overflow.com/tickets/198
506 | http://tickets.pm4overflow.com/tickets/506
607 | http://tickets.pm4overflow.com/tickets/607

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-4-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-4-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-4-processmaker.ci.processmaker.net

**Review by agustinbusso — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-4-processmaker.ci.processmaker.net

**Pull request merged**
