### PR TITLE
Laravel 7.x Shift

### PR DESCRIPTION
**Pull request by ryancooley**
This pull request includes the changes for upgrading to Laravel 7.x. Feel free to commit any additional changes to the `shift-61116` branch.

**Before merging**, you need to:

- Checkout the `shift-61116` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by ryancooley** [comment]
:warning: Shift detected a custom namespace. Laravel now recommends keeping the default `App` namespace. While it was available to customize in previous versions using `app:name`, this command was removed in Laravel 6.

Shift recommends changing this to align with Laravel and improve its automation. After doing so, you are welcome to request a rerun of this Shift.

**Comment by ryancooley** [comment]
:x: Shift was unable to find your _Exception Handler_. Laravel 7 upgraded to Symfony 5 which passes instances of the `Throwable` interface instead of `Exception`.

You should compare your `app/Exceptions/Handler.php`  with the [default Laravel 7 version](https://github.com/laravel-shift/laravel-7.x/blob/master/app/Exceptions/Handler.php) to finalize any changes.

**Comment by ryancooley** [comment]
:information_source: Laravel 7 moved the Authentication components into a separate [`laravel/ui` package](https://github.com/laravel/ui), which includes the _make_ commands as well as the traits related to authentication.

Shift added this dependency for convenience. However, if you do not plan to use the Authentication components, you may remove this dependency as well as the `Auth` controllers from your application.

**Comment by ryancooley** [comment]
:warning: Laravel 7 removed "factory types". While available, this was undocumented since [Laravel 5.2](https://laravel.com/docs/5.2/testing#model-factories). Since then the preferred method has been [factory states](https://laravel.com/docs/7.x/database-testing#factory-states).

Shift converted usages of `$factory->defineAs()` to `$factory->state()`. However, you should [review this commit](https://github.com/ProcessMaker/processmaker/pull/4347/commits/0fff9f96892dbd3328397e87abf6d5e33ff6207f?w=1) and run your tests to see if any additional changes to your _factory states_ are necessary.

**Comment by ryancooley** [comment]
:warning: The `MAIL_DRIVER` environment variable was renamed in Laravel 7 to `MAIL_MAILER` in order to support multiple mail configurations.

Shift attempted to [automate this change](https://github.com/ProcessMaker/processmaker/pull/4347/commits/50121f46f0fdb9cca22b68a593aafe1194ca6b77?w=1), but you should review any additional environment configuration and update to the new variable name.

**Comment by ryancooley** [comment]
:warning: Shift upgraded your configuration files by defaulting them and merging your _true customizations_. These include values which are not changeable through core `ENV` variables.

You should [review this commit](https://github.com/ProcessMaker/processmaker/pull/4347/commits/db047768c27f2759c4f61242b2c60ab526d5948d?w=1) for additional customizations or opportunities to use new `ENV` variables. If you have a lot of customizations, you may undo this commit with `git revert db047768` and make the [config file changes](https://github.com/laravel-shift/laravel-6.0/pull/7/commits/e3379a9dcc2b08adf5934a99148366838371bc68) manually.

**Comment by ryancooley** [comment]
:information_source: Shift [updated your dependencies](https://github.com/ProcessMaker/processmaker/pull/4347/commits/fc960273eabd67da3c6c65d37c0d75225ebc5364?w=1) for Laravel 7. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 7.

Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling any additional package incompatibilities.

**Comment by ryancooley** [comment]
:warning: In Laravel 7, all of the `assertSee` methods now automatically escape the expected values.

If you were manually escaping the values passed to these methods, you no longer need do so. If you were asserting values containing HTML that should not be escaped, you may set the new `escaped` argument to `false`.

Shift found the instances of these assertions within:

- [ ] tests/Browser/RequestsTest.php
- [ ] tests/Feature/AboutTest.php
- [ ] tests/Feature/Admin/GroupTest.php
- [ ] tests/Feature/Admin/UserTest.php
- [ ] tests/Feature/Api/ChangePasswordTest.php
- [ ] tests/Feature/Api/GroupsTest.php
- [ ] tests/Feature/Api/ProcessRequestsTest.php
- [ ] tests/Feature/Api/ScriptsTest.php
- [ ] tests/Feature/Api/UsersTest.php
- [ ] tests/Feature/EditDataTest.php
- [ ] tests/Feature/FlashMessageTest.php
- [ ] tests/Feature/Processes/EnvironmentVariablesTest.php
- [ ] tests/Feature/Processes/ScreenTest.php
- [ ] tests/Feature/Processes/ScriptsTest.php
- [ ] tests/Feature/ProcessesTest.php
- [ ] tests/Feature/RequestTest.php
- [ ] tests/Feature/TasksTest.php

**Comment by ryancooley** [comment]
:warning: Shift found potential uses of the `different` validation rule. In Laravel 7, this rule will fail if one of the specified parameters is missing from the request. As this was likely the expected behavior, it should not affect your validation. Nonetheless you should be aware of this change.

**Comment by ryancooley** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 5. If you are directly interacting with any Symfony component, you should review the [Symfony change log](https://github.com/symfony/symfony/blob/5.x/UPGRADE-5.0.md) for additional changes.

**Comment by ryancooley** [comment]
:warning: Shift detected you are using a Laravel package like Horizon or Nova which may need to have its published assets regenerated after upgrading. Be sure to use `artisan` to _republish_ these assets as well as `php artisan view:clear` to avoid any errors.

**Comment by ryancooley** [comment]
:warning: Laravel 7.x has reached [end of life](https://laravelversions.com/). It no longer receives bug fixes or security updates. Shift recommends continuing to upgrade to the latest version (Laravel 9.x).

For tips on running multiple Shifts effectively, watch [upgrading old Laravel applications](https://laravelshift.com/videos/upgrading-old-laravel-applications).

**Comment by nolanpro** [comment]
Re-running swift with updated develop branch

**Pull request closed without merging**
