### PR TITLE
Add self service support for users

### PR DESCRIPTION
**Pull request by sanjacornelius**
**Jira Ticket**

https://processmaker.atlassian.net/browse/FOUR-2913

<h2>Changes</h2>

This PR adds self-service support for users by including the `assignedUsers` array in the `self_service_groups` array.

<h2>To Test</h2>

- Ensure to have additional users created.
- Create a process and set the 'Assignment Rules' to 'Self Service' with a user assigned.
- Log in as the assigned user and view the 'Self Service' tasks, open the task.

**Expected Behavior**

When selecting the task the 'Claim Task' button appears with no errors.

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2913-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2913-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2913-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2913-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2913-processmaker.ci.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2913-processmaker.ci.processmaker.net

**Pull request merged**
