### PR TITLE
Run  terser in parallel to fix build problem

### PR DESCRIPTION
**Pull request by caleeli**
Run  terser in parallel to fix build problem

```
/js/processes/modeler/initialLoad.js from Terser
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/home/circleci/opt/processmaker/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/ChildProcessWorker.js:191:21)
    at ChildProcessWorker._onExit (/home/circleci/opt/processmaker/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/ChildProcessWorker.js:268:12)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)

```

### CODE REVIEW

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-terser_issues-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-terser_issues-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-terser_issues-processmaker.ci.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-terser_issues-processmaker.ci.processmaker.net

**Pull request merged**
