### PR TITLE
404 error editing Rule Expression assignment and Group of users

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
Fixes [FOUR-3549](https://processmaker.atlassian.net/browse/FOUR-3549)

- Verify id group in call load resource

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3549-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3549-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3549-processmaker.ci.processmaker.net

**Review by ryancooley — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3549-processmaker.ci.processmaker.net

**Pull request merged**
