### PR TITLE
Bugfix/FOUR-5538: [27478] System Signals able to be deleted, edited, cause processes to not work

### PR DESCRIPTION
**Pull request by agustinbusso**
## Issue & Reproduction Steps
Signals that are present in processes or in system processes should not be deleted.

- Have an instance with PM 4.2.x
- Go to Designer, Signals
- Find the signals that belong to the package-advanced-user-manager package, see the image attached
- Delete those signals
- Try a request with any existing process, you will the error attached: Element "sync_assignment" was not found

## Solution
- In the **index** method in signals controller, changed the parameter **includeSystemProcesses** to true to retrieve signals with system processes, to disable the delete button in frontend.
- In the **destroy** method in signals controller, check if signals are present in some process or system process and abort the deleting operation.

## How to Test

**Case 1**
- Go to designer / signals and create a signal
- After create the signal the icon to delete the signal should be VISIBLE
- Click the delete button, the signal should be deleted

**Case 2**
- Go to designer / signals and create a signal
- Go to designer / processes and create a process
- Add a signal event in the process and configure the signal previously created. Save the process
- Go to designer / signals again, the signal you created previously should have the delete button disabled
- Try to delete the previous signal via postman. You should receive an error message "Signals present in processes and system processes cannot be deleted."

**Case 3**
- Install advance-user-manager package
- Go to designer / signals and notice that should be present 3 new system signals ("sync_assignment",	"escalate_task", "delegate_task")
- That system signals should have the delete button disabled
- Try to delete some of that system signals via postman. You should receive an error message "Signals present in processes and system processes cannot be deleted."

Run test cases under tests/Feature/Api/SignalTest.php

**Working video**
P.S.: Ignore the word "bya" in the video (is via)

https://user-images.githubusercontent.com/90727999/157320329-3f0f8392-5e0e-45cc-a54d-a1ac02e3d028.mov

## Related Tickets & Packages
- [FOUR-5538](https://processmaker.atlassian.net/browse/FOUR-5538)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5538-processmaker.ci.processmaker.net

**Review by danloa — CHANGES_REQUESTED** [review]
An additional improvement that we need to add: a System signals should not be updated. Editing should be disabled for these signals.

**Comment by agustinbusso** [comment]
Disabled editing for system signals. Working video:

https://user-images.githubusercontent.com/90727999/157478464-93a90a7b-824b-4f25-b2de-3961d60bb2f0.mov

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5538-processmaker.ci.processmaker.net

**Review by danloa — APPROVED** [review]

**Comment by agustinbusso** [comment]
Added tooltips for disabled buttons:

https://user-images.githubusercontent.com/90727999/158445639-7968d195-7ebd-40ec-a480-666f8eaf6753.mov

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5538-processmaker.ci.processmaker.net

**Pull request merged**
