### PR TITLE
Implement 'Configure Template' Action for Screen Templates

### PR DESCRIPTION
**Pull request by sanjacornelius**
## Issue & Reproduction Steps
This PR introduces the 'Configure Template' action in the Screen Template option menu, allowing users to reconfigure a screen template after creation. 

## Solution

- Refactored `configure.blade.php` file to handle configurations for both Process Templates and Screen Templates.
- Initial implementation of the `deleteMediaImages` method for templates (observation [FOUR-14664](https://processmaker.atlassian.net/browse/FOUR-14664) has been created).
- Implemented the configure method specifically for Screen Templates.

## How to Test

1. Create a New Screen Template.
2. Navigate to the screen template listing page.
3. Select 'Configure Template' from the Option menu for the desired template.
4. Verify redirection to a new page displaying the screen template configurations.
5. Update values in the screen template configurations.
6. Click 'Save'.
7. Ensure the template is saved successfully.
8. Verify proper error messages are displayed upon failure.

**Note:**
Errors may occur when removing thumbnails. An additional [observation](https://processmaker.atlassian.net/browse/FOUR-14664) ticket has been created to address this issue.

## Related Tickets & Packages
- [FOUR-14502](https://processmaker.atlassian.net/browse/FOUR-14502)

ci:next

.

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

[FOUR-14664]: https://processmaker.atlassian.net/browse/FOUR-14664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-14502]: https://processmaker.atlassian.net/browse/FOUR-14502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-92ec3db6dd.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-92ec3db6dd.engk8s.processmaker.net

**Review by mcraeteisha — APPROVED** [review]
Approved!

**Comment by estebangallego** [comment]
> Hey @ryancooley , it looks like this failing test is related to the AB Testing package and isn't directly related to the changes in this PR.

Hey @sanjacornelius, I just merged next to this branch to resolve those issues.

**Pull request merged**
