### PR TITLE
Epic/FOUR-9675: AI Script Generation and Co-Pilot for scripting

### PR DESCRIPTION
**Pull request by agustinbusso**
**Figma**
https://www.figma.com/file/HPlbIAFk5pPLvHX6vyUN3K/Fall-23?type=design&node-id=911-265155&mode=design&t=FqPDbvhyOck2MpvF-0

**PI Planning document**
https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3149299713/AI+Script+Generation+and+Co-Pilot+for+scripting

**Epic**
https://processmaker.atlassian.net/browse/FOUR-9675

**Related PR's**
https://github.com/ProcessMaker/package-ai/pull/15

ci:deploy
ci:package-ai:epic/FOUR-9675

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-f549c3cda7.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-f549c3cda7.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-f549c3cda7.eng.processmaker.net

**Comment by agustinbusso** [comment]
Closing due a problem with deploy

**Pull request closed without merging**
