### PR TITLE
feature/FOUR-17894 : [FALL] Per Launchpad Dashboard

### PR DESCRIPTION
**Pull request by pmPaulis**
## Per Launchpad Dashboard
Integrating an analytics iframe within the Process Launchpad will allow users to directly view process-specific analytics information. This feature will consolidate relevant data and insights into a single interface, reducing the need to switch between multiple tools and platforms. Users will benefit from immediate access to critical analytics, leading to more efficient and effective process management.

##  PRD
[Per Launchpad Dashboards](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3587768324/Per+Launchpad+Dashboards)
 

##  FIGMA
[Fall 2024](https://www.figma.com/design/Jfl3HAOx28TVHMl7cHJNIP/Fall-2024?node-id=1331-12898&t=fql4A9LOySuWSSCT-0)

## Solution

- As a ProcessMaker User, I want to be able to see the Custom Dashboard with the UI Style that Process Intelligence has in Analytics 
- As a ProcessMaker User, I want to be able to open the Analytics Dashboards (from PI) build for that specific process.

## How to Test
1. Access the LaunchPad
2. Open a Process
3. Find the Custon Chart displayed with the PI UI Style

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-17894

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-c5be8e57fb.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-c5be8e57fb.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-c5be8e57fb.engk8s.processmaker.net

**Review by fagubla — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-c5be8e57fb.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-c5be8e57fb.engk8s.processmaker.net

**Pull request merged**
