### PR TITLE
FOUR-3676: Fix for Super Admin toggle working inconsistently

### PR DESCRIPTION
**Pull request by ryancooley**
## Changes
- Refactors permissions UI and API call to better handle changing the is_administrator property of a user
- Prevents multiple API calls from being made when they are not necessary
- Updates inline API documentation

## Tickets
- http://tickets.pm4overflow.com/tickets/164
- https://processmaker.atlassian.net/browse/FOUR-3676

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3676-processmaker.ci.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3676-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3631-for-4-1-processmaker.ci.processmaker.net

**Pull request merged**
