### PR TITLE
Allow scripts to be run in sync mode

### PR DESCRIPTION
**Pull request by nolanpro**
Fixes https://processmaker.atlassian.net/browse/FOUR-3139

- Api calls to execute scripts run in sync mode instead of waiting for a broadcast event on the queue
- Data sources directly connect to the data source api instead of going through a service task

Requires
- vue-form-elements: https://github.com/ProcessMaker/vue-form-elements/pull/264
- screen-builder: https://github.com/ProcessMaker/screen-builder/pull/972
- web-entry: https://github.com/ProcessMaker/package-webentry/pull/114

Steps to deploy:
- After vue-form-elements is published to npmjs, update the version in the screen-builder pr and core (this pr)

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3139-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3139-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3139-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3139-processmaker.ci.processmaker.net

**Review by caleeli — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3139-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3139-processmaker.ci.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3139-processmaker.ci.processmaker.net

**Pull request merged**
