### PR TITLE
Only get next user by rule if assignment type is rule_expression

### PR DESCRIPTION
**Pull request by nolanpro**
Fixes https://processmaker.atlassian.net/browse/FOUR-3380

- Same fix in 4.1.19. This is just to bring it into 4.2

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3380-develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3380-develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3380-develop-processmaker.ci.processmaker.net

**Review by caleeli — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3380-develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Pull request merged**
