### PR TITLE
Ticket #722: Horizon Not Loading

### PR DESCRIPTION
**Pull request by ryancooley**
## Changes
- Refactors Queue Management page to utilize an iframe rather than attempting to embed the code directly into our design
  - Fixes an issue where the ProcessMaker styles were being overridden by Horizon's styles
  - Fixes an issue where scrolling did not work properly
- Fixes an issue caused by gitignore where Horizon JS and CSS assets were not loading on many instances

## Screenshots

Before
Screen Shot 2021-09-15 at 1 35 06 PM

After
Screen Shot 2021-09-15 at 1 34 40 PM

## Tickets
- http://tickets.pm4overflow.com/tickets/722

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-722-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-722-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-722-processmaker.ci.processmaker.net

**Review by runyan-co — APPROVED** [review]
Looks good and works for me on QA (https://bugfix-ticket-722-processmaker.ci.processmaker.net/admin/queues) and a local build.

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-722-processmaker.ci.processmaker.net

**Pull request merged**
