### PR TITLE
Error when trying to configure a Data Connector with third-party API endpoints

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
Fixed [FOUR-3142](https://processmaker.atlassian.net/browse/FOUR-3142)

- remove old parameter outboundConfig

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3142-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3142-processmaker.ci.processmaker.net

**Review by ryancooley — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3142-processmaker.ci.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3142-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Pull request merged**
