### PR TITLE
QA Observation Bugfix/FOUR-13079: The column layout of the request tables is different from that of Figma.

### PR DESCRIPTION
**Pull request by CarliPinell**
## How to Test
- Create a new request
- Open Process with request in "Open in Launchpad"
- Check Request Tab columns

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-13079

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.
ci:deploy
ci:next

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-1f6e236610.engk8s.processmaker.net

**Comment by pmPaulis** [comment]
@CarliPinell 
The following columns needs to show according the PO comments, the PRD was updated
**MY REQUEST**
CASE #
CASE TITLE
STATUS
STARTED
COMPLETED

**MY TASK**
CASE #
CASE TITLE
TASK NAME
STATUS
DUE DATE

**Review by fagubla — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-1f6e236610.engk8s.processmaker.net

**Comment by pmPaulis** [comment]
@CarliPinell 
The styles for the columns CASE # and CASE TITLE is missing:
image
Expected is
image

**Review by pmPaulis — APPROVED** [review]

**Comment by pmPaulis** [comment]
I review the last commit.
The colums CASE # and CASE TITLE is showing with the correc styles
The link to the tab My Task is working like Tasks
image

**Pull request merged**
