### PR TITLE
Fix Self Service List

### PR DESCRIPTION
**Pull request by caleeli**
The current Self Service list (in 4.1.0) is adding incorrectly the logged USER_ID to the `where` filter, but it should be null to get the self service tasks.

This PR fixes the Self Service filter.

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2967-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2967-processmaker.ci.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2967-processmaker.ci.processmaker.net

**Review by danloa — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2967-processmaker.ci.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2967-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-17-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2967-processmaker.ci.processmaker.net

**Pull request merged**
