### PR TITLE
Add log messages from packages on import

### PR DESCRIPTION
**Pull request by caleeli**
Required by: https://github.com/ProcessMaker/connector-send-email/pull/125
Related to: https://processmaker.atlassian.net/browse/FOUR-2528
Fixes: https://processmaker.atlassian.net/browse/FOUR-2545

- Add log methods that could be used by packages to register messages on importing process.
- Add a validation to check the scripts assigned to watchers

Since the file was generated by an old version of PM4, it does not contains the scripts assigned to watchers, causing an exception during the import process. It was validated and fixed so the process can be imported but without the missing resource.

image

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2528-processmaker.ci.processmaker.net

**Review by GooseCoder — APPROVED** [review]
PR approved

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2528-processmaker.ci.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Pull request merged**
