### PR TITLE
FOUR-3359: Select List issue on ProcessMaker v4.1.18

### PR DESCRIPTION
**Pull request by danloa**
Fixes [https://processmaker.atlassian.net/browse/FOUR-3359](https://processmaker.atlassian.net/browse/FOUR-3359)

The solution is alread present in 4.2.6. I applied the commit 856466c7e4232828a5e7b42aa6b2967b10d9ad0d  to resolve the issue.

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3359-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3359-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3359-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3359-processmaker.ci.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3359-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-19-processmaker.ci.processmaker.net

**Pull request merged**
