### PR TITLE
FOUR-5882:   Terminate event not closing all open tasks

### PR DESCRIPTION
**Pull request by danloa**
## Issue & Reproduction Steps

-     Import the process
-     Run a new request, you should see 3 tasks: Task1, Task2 and Terminate task
-     Open "Terminate task" and submit it

Even when the Terminate End Event is triggered, Task 1 and Task 2 are still active. A terminate should close all open tokens of a request.

## Solution
- Added listener that persists closed tokens during a terminate end event.

## How to Test
Follow the steps to reproduce and:
- Verify that when submitting "Task 1" it arrives to a normal end event and  just Task 1 is closed. Task 2 and "Terminate Task" should be active
- Verify that when submitting "Terminate Task", all  tasks are closed and the request completed

## Related Tickets & Packages
- [https://processmaker.atlassian.net/browse/FOUR-5882](https://processmaker.atlassian.net/browse/FOUR-5882)

## Code Review Checklist
- [x] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [x] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [x] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [x] This solution fixes the bug reported in the original ticket.
- [x] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [x] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [x] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [x] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5882-processmaker.ci.processmaker.net

**Review by caleeli — CHANGES_REQUESTED** [review]
@danloa based on your analysis the fix should be applied in Nayra instead of PM4Core (to avoid overwrite the termination logic) consider the following suggestion: 

https://github.com/ProcessMaker/nayra/pull/216

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5882-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5882-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5882-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5882-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5882-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5882-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5882-processmaker.ci.processmaker.net

**Comment by danloa** [comment]
This PR is replaced with https://github.com/ProcessMaker/nayra/pull/217

**Pull request closed without merging**
