### PR TITLE
Show Task Info for Self Service

### PR DESCRIPTION
**Pull request by sanjacornelius**
**Jira Ticket**

https://processmaker.atlassian.net/browse/FOUR-3144

<h2>Changes</h2>

- Remove conditional that hide the task info when self-service was enabled
- Add a warning alert message when submitting the form and the task has not been claimed.

**Video**

https://user-images.githubusercontent.com/52755494/119040192-f353eb80-b969-11eb-9942-9b3467aed18e.mov

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3144-processmaker.ci.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3144-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3144-processmaker.ci.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3144-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3144-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3144-processmaker.ci.processmaker.net

**Pull request merged**
