### PR TITLE
Fix 'Undefined index: Assign to' error when escalating a self-service task

### PR DESCRIPTION
**Pull request by sanjacornelius**
**Jira Ticket**
https://processmaker.atlassian.net/browse/FOUR-3047

<h2>Changes</h2>

Hides the `Escalate to manager` button when there is no user assigned to the self-service task. The self-service task must be claimed before escalating to a manager. 

Screen Shot 2021-04-23 at 10 54 10 AM

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3047-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3047-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3047-processmaker.ci.processmaker.net

**Review by caleeli — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3047-processmaker.ci.processmaker.net

**Pull request merged**
