### PR TITLE
FOUR-2223: Translations Update - Modeler translations

### PR DESCRIPTION
**Pull request by danloa**
Related to [https://processmaker.atlassian.net/browse/FOUR-2223](https://processmaker.atlassian.net/browse/FOUR-2223)

Modeler translation didn't load properly. At times the translation object wasn't available and translations set in vue components were not working.  In this PR I introduce a timeout to await for the translations object. When it is available, the modeler component is rendered.

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2223-c-processmaker.ci.processmaker.net

**Review by caleeli — CHANGES_REQUESTED** [review]
in `bootstrap.js` looks like there is a Promise for i18n loading:
```
i18next.use(Backend).init({
  ...
}).then(() => { translationsLoaded = true; })

```
It could be better to use it instead of setTimeout.
Something like:
```
window.i18nPromise = i18next.use(Backend).init({...});
```
then
```
window.i18nPromise.then(() => renderWhenTranslationAvailable());
```
if `init` is not a Promise, you could add one in `bootstrap.js`

**Review by caleeli — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2223-c-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Pull request merged**
