### PR TITLE
[35931] EcoBank - Password field with autocomplete enabled

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
## Issue & Reproduction Steps
Autocomplete is missing in the form login.

## Solution
- add validation for autocomplete
## How to Test
login with user

## Related Tickets & Packages
- [FOUR-13943](https://processmaker.atlassian.net/browse/FOUR-13943)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy

[FOUR-13943]: https://processmaker.atlassian.net/browse/FOUR-13943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-c0ec4e9e95.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-c0ec4e9e95.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-c0ec4e9e95.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-c0ec4e9e95.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-c0ec4e9e95.engk8s.processmaker.net

**Comment by boliviacoca** [comment]
@marcoAntonioNina  in sync with @ryancooley, @MauricioVeliz  and PO, it has been decided to push back on it because it would make us vulnerable, this PR would be close.

**Pull request closed without merging**
