### PR TITLE
Display error when validating MI data input

### PR DESCRIPTION
**Pull request by caleeli**
Requires: https://github.com/ProcessMaker/nayra/pull/202

This PR includes:

- Show Activity Errors including errors from MultiInstance data input validations

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3599-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3599-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3599-processmaker.ci.processmaker.net

**Review by nolanpro — APPROVED** [review]
Verified with non-sequential array on a task with parallel MI. Prior to the fix, it was throwing an error `Undefined offset: 1`. After the fix, the error has a better explanation. Verified that if a boundary error is on the task it correctly goes down that path.

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3599-processmaker.ci.processmaker.net

**Pull request merged**
