### PR TITLE
Error 401, when I try to configure my select list with data connector

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
Fixed [FOUR-3207](https://processmaker.atlassian.net/browse/FOUR-3207)

- stop 401 error consuming endpoints with data-sources

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3207-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3207-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3207-processmaker.ci.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3207-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3032-processmaker.ci.processmaker.net

**Pull request merged**
