### PR TITLE
ticket-513: SANITY-Timer Start Event - Multiple Request Started

### PR DESCRIPTION
**Pull request by danloa**
Fixes [http://tickets.pm4overflow.com/tickets/513](http://tickets.pm4overflow.com/tickets/513)

### CODE REVIEW

**Review by caleeli — CHANGES_REQUESTED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-513-processmaker.ci.processmaker.net

**Review by caleeli — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-513-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-513-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-513-processmaker.ci.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-513-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Pull request merged**
