### PR TITLE
feature/FOUR-17027: A "cancelled" error is displayed when clicking on the ascending and descending options in notifications

### PR DESCRIPTION
**Pull request by luNunezProcessmaker**
## Issue & Reproduction Steps
We see that it shows us a canceled message, wanting to sort the notification columns

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-17027

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-3f22595b82.engk8s.processmaker.net

**Comment by pmPaulis** [comment]
@luNunezProcessmaker 
The mensage is showed above the list and the message Canceled is showed in the tab changes too

https://github.com/user-attachments/assets/6e8460d7-855c-49cf-a3c1-cfc18d7efb61

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-3f22595b82.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-3f22595b82.engk8s.processmaker.net

**Review by fagubla — APPROVED** [review]

**Comment by fagubla** [comment]
there is not showing an alert error and neither an error in the console

Screenshot 2024-08-01 at 15 52 54

**Pull request merged**
