### PR TITLE
Fix params replacing

### PR DESCRIPTION
**Pull request by caleeli**
Fixes: https://processmaker.atlassian.net/browse/FOUR-3735

This PR fixes the outbound configuration and check the parameters arrives properly

- Fix list of params
- Add `mustache`, `feel` labels to clarify the expressions format
- Add `mustache/feel` switch to choose the right format when required
- Fix the returned error message from endpoint

### Examples
_**Request variables:**_
1. foo = "bar"
2. number = 100
3. _request = { id: 1001 }
4. array = [1, 2, 3]
_**Dataconnector:**_

- URL = `http`://example.com/api/`{{version}}`/resource?param1=`{{param1}}`
- Params:
  - param2 = value
  - param3 = {{ param3 }}
  - param4 = {{ param4 }} *required

_**Outbound configuration:**_
- version = {{ number }}   // `{ Mustache }`
- param1 = foo   // `{ Mustache }`
- param3 = foo   // `feel`

_**Result:**_
URL: `http`://example.com/api/`100`/resource?param1=`foo`&param2=`value`&param3=`bar`&param4=
**Note**: `param4` is mandatory but it is empty, therefore it is added to the URL but with an empty value

Mustache syntax: 
image
FEEL syntax:
image
Outbound configuration:
image

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3735-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3735-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3735-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3735-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3735-processmaker.ci.processmaker.net

**Review by ryancooley — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3735-processmaker.ci.processmaker.net

**Pull request merged**
