### PR TITLE
Update Swagger Docs

### LINKED ISSUE #2150: Update Swagger
Update to fix all of the doc changes identified by QA.

### PR DESCRIPTION
**Pull request by sanjacornelius**
Updated Swagger documentation based on the failed endpoints within the [Api Endpoint Checks spreadsheet](https://docs.google.com/spreadsheets/d/10WHT_omC3XJJ9Hn1H8fkHN0wh7UIoV1ouO2C8pKj8jo/edit#gid=0).

closes #2150

### CODE REVIEW

**Comment by velkymx** [comment]
Task Assignments also seems wrong. I should need to specify an id to get the assignments

**Comment by sanjacornelius** [comment]
> For the File API this line seems wrong: /files/{file_id}/contents should be GET on /files/{file_id}

The endpoint /files/{file_id}/contents exports the image to be downloaded and the endpoint /files/{file_id} returns the single data object.

**Comment by sanjacornelius** [comment]
> Task Assignments also seems wrong. I should need to specify an id to get the assignments

Correct I noted in the [api endpoint check spreadsheet](https://docs.google.com/spreadsheets/d/10WHT_omC3XJJ9Hn1H8fkHN0wh7UIoV1ouO2C8pKj8jo/edit#gid=0) that this endpoint needed to be created. It's the last fail on the list. Would you like for me to go ahead and create this endpoint?

**Comment by velkymx** [comment]
> > Task Assignments also seems wrong. I should need to specify an id to get the assignments
> 
> Correct I noted in the [api endpoint check spreadsheet](https://docs.google.com/spreadsheets/d/10WHT_omC3XJJ9Hn1H8fkHN0wh7UIoV1ouO2C8pKj8jo/edit#gid=0) that this endpoint needed to be created. It's the last fail on the list. Would you like for me to go ahead and create this endpoint?

@sanjacornelius remove it from swagger.

**Comment by sanjacornelius** [comment]
> > > Task Assignments also seems wrong. I should need to specify an id to get the assignments
> > 
> > 
> > Correct I noted in the [api endpoint check spreadsheet](https://docs.google.com/spreadsheets/d/10WHT_omC3XJJ9Hn1H8fkHN0wh7UIoV1ouO2C8pKj8jo/edit#gid=0) that this endpoint needed to be created. It's the last fail on the list. Would you like for me to go ahead and create this endpoint?
> 
> @sanjacornelius remove it from swagger.

It is now removed from swagger.

**Pull request merged**
