### PR TITLE
Identity & Access Management: Cookie security

### PR DESCRIPTION
**Pull request by gustavo-romero**
Proposal to set the following session cookie security best practices for session management as a default:

- Set the _secure_ cookie attribute (Secure channel for session cookie transmission)
- Set the _expire_on_close_ attribute (End session on browse close)
- Set the _Same-Site_ cookie flag (Prevent CSRF)

### CODE REVIEW

**Comment by velkymx** [comment]
Can you provide a test for this functionality?

**Comment by gustavo-romero** [comment]
> Can you provide a test for this functionality?

Here's a test for the cookie flags:
`curl --silent --output /dev/null --dump-header - 'https://<serverFQDN>/' | grep set-cookie`

Should return a similar output:
`set-cookie: processmaker_session=eyJpdiI6IjZQNStyNGxURGRiOTk3MzFxVWdib1E9PSIsInZhbHVlIjoiOEhtWHRSMHhoUytCVWxLYm9sMzJlaTdxSVEyNG5pXC9yOUJKN3RXVDFzUVhxUnoyaU5lWHcrQmxEeVRFNzRieW0iLCJtYWMiOiIxMjRkMDYwOWM2MzVmYmUwZDJiOTQwMGVlYTg3NTQ3OWI5ZDI3MzYxMmU3NTA2OWU5ZjUxNThiMjZjODViZGFkIn0%3D; path=/;samesite=Lax; secure; httponly`

To test _expire_on_close_ , it's a manual test - login to the application, close the browser, open the browser again (with "recently closed" tab), and the session should be terminated (without the need of deleting browser cache/cookies). I've successfully tested this in the latest chromium build (got redirected to login).

**Comment by nolanpro** [comment]
@gustavo-romero since this is in your personal repository, I can not add a unit test. Please add the following to tests/Feature/SessionTest.php

Because these settings effect how the browser handles cookies, and we do not currently run browser tests, the best we can do it check that they are correctly being set in the header.

```
<?php

namespace Tests\Feature;

use Tests\TestCase;

class SessionTest extends TestCase
{
    public function test()
    {
        $response = $this->get('/');

        // check 'expire_on_close' => true,
        $this->assertEquals(0, $response->headers->getCookies()[0]->getExpiresTime());

        // check 'path' => '/;samesite=Lax',
        $this->assertEquals('/;samesite=Lax', $response->headers->getCookies()[0]->getPath());

        // Check 'secure' => env('SESSION_SECURE_COOKIE', true),
        $this->assertTrue($response->headers->getCookies()[0]->isSecure());
    }
}
```

**Comment by gustavo-romero** [comment]
> @gustavo-romero since this is in your personal repository, I can not add a unit test. Please add the following to tests/Feature/SessionTest.php
> 
> Because these settings effect how the browser handles cookies, and we do not currently run browser tests, the best we can do it check that they are correctly being set in the header.
> 
> ```
> <?php
> 
> namespace Tests\Feature;
> 
> use Tests\TestCase;
> 
> class SessionTest extends TestCase
> {
>     public function test()
>     {
>         $response = $this->get('/');
> 
>         // check 'expire_on_close' => true,
>         $this->assertEquals(0, $response->headers->getCookies()[0]->getExpiresTime());
> 
>         // check 'path' => '/;samesite=Lax',
>         $this->assertEquals('/;samesite=Lax', $response->headers->getCookies()[0]->getPath());
> 
>         // Check 'secure' => env('SESSION_SECURE_COOKIE', true),
>         $this->assertTrue($response->headers->getCookies()[0]->isSecure());
>     }
> }
> ```

Thanks @nolanpro, it's done.

**Review by velkymx — APPROVED** [review]

**Pull request merged**
