### PR TITLE
Test PM4 services

### PR DESCRIPTION
**Pull request by caleeli**
Resolves: https://processmaker.atlassian.net/browse/FOUR-3054

This PR implements a command to test the PM4 services:

```
php artisan processmaker:test
```

TestStatus mp4

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3054-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3054-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3054-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3054-processmaker.ci.processmaker.net

**Review by marcoAntonioNina — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3054-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2974-processmaker.ci.processmaker.net

**Pull request merged**
