### PR TITLE
Fix params replacements and output mapping

### PR DESCRIPTION
**Pull request by caleeli**
This PR fixes params replacements in DataConnectors.
Requires: https://github.com/ProcessMaker/package-data-sources/pull/180
Requires: https://github.com/ProcessMaker/screen-builder/pull/1038

https://user-images.githubusercontent.com/8028650/129282109-45d11006-6c2c-43e7-8b72-b5d5a273b5b6.mp4

PROCESS: [Test DataConnector.json.txt](https://github.com/ProcessMaker/processmaker/files/6979034/Test.DataConnector.json.txt)

COLLECTION: [persons.json.txt](https://github.com/ProcessMaker/processmaker/files/6979036/persons.json.txt)
Notes to test:
- Make sure you add `pmql` as a non required parameter into the ListAll endpoint
- Make sure the body of the creation and update endpoints have the following body:
```
{
    "data": {
        "dni": "{{dni}}",
        "name": {
            "first": "{{first}}",
            "last": "{{last}}"
        }
    }
}
```

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-563-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-563-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-563-processmaker.ci.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-563-processmaker.ci.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-563-processmaker.ci.processmaker.net

**Pull request merged**
