### PR TITLE
feature/FOUR-13461: [SPRING] Task/Request Containers Collapsable

### PR DESCRIPTION
**Pull request by pmPaulis**
## Issue & Reproduction Steps
Task/Request Containers Collapsable
**PRD**
https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3214508033/Task+Request+Containers+Collapsable 
**FIGMA**

https://www.figma.com/file/Tr2bVMtC4jr6KGWBvM6Vtp/Spring-24?type=design&node-id=11284-98933&mode=design&t=NexkPfoaldTwJzOA-0

## Solution
- List the changes you've introduced to solve the issue.

## Issue & Reproduction Steps
Task/Request Containers Collapsable

## How to Test
Open an request or taks and review the new collapsible section

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-13461

## Packages PR Related
https://github.com/ProcessMaker/package-comments/pull/112

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next
ci:package-comments:feature/FOUR-13461

### CODE REVIEW

**Review by fagubla — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-fd3b185050.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-fd3b185050.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-fd3b185050.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-fd3b185050.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-fd3b185050.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-fd3b185050.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-fd3b185050.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-fd3b185050.engk8s.processmaker.net

**Pull request merged**
