### PR TITLE
[4.2] Ticket #734: Undeleting Users blocked by Unique Email requirement

### PR DESCRIPTION
**Pull request by runyan-co**
Allows soft deleted users with a non-unique email to be restored without failing.

Ticket #734:
http://tickets.pm4overflow.com/tickets/734

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-734_4-2-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-734_4-2-processmaker.ci.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-734_4-2-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-734_4-2-processmaker.ci.processmaker.net

**Pull request merged**
