### PR TITLE
Enhance + Asset and Duplicate Asset Modals

### PR DESCRIPTION
**Pull request by sanjacornelius**
ci:next
ci:package-projects:task/FOUR-10237
ci:deploy

# Issue
Tickets: [FOUR-10237](https://processmaker.atlassian.net/browse/FOUR-10237) & [FOUR-10298](https://processmaker.atlassian.net/browse/FOUR-10298)

To improve the user experience on the Asset Listing page, we propose the following enhancements for the "+ Asset" button:

- Asset Type Selection: Upon selecting an asset type, an additional pane will appear, featuring:

- Search Bar: This bar allows users to search for existing assets.

- +[[Asset_Type]] Button: Users can click this button to create a new asset of the selected type.

- List of Existing Assets: Below the search bar, a list of currently existing assets will be displayed.

NOTE: If the user adding the asset lacks designer permissions (for Screens, Scripts, Processes, etc.), the list of existing assets shown under the search bar will only include assets accessible via other projects. Additionally, users can create new assets exclusively from this screen.

Updates were also made to the UI for the Duplicate Asset Model. Mockups can be seen on ticket [FOUR-10298.](https://processmaker.atlassian.net/browse/FOUR-10298)

# How to Test
1. Go to branch `task/FOUR-10237` in `core`.
2. Go to branch `task/FOUR-10237` in `package-projects`.
3. Go Designer → Projects. Have a Project created. Open the Project.
4. From the +ASSET button, add new Assets to the Project. 
	- Test adding existing assets as well as creating new assets.
5. Once you have assets created, from the Ellipsis Menu on the assets listing, test Duplicating Assets.
6. Also test Removing Assets from a Project via the Remove button in the asset Ellipsis Menu.

# Code Review Checklist

- [ ]  I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ]  This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ]  This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ]  This solution fixes the bug reported in the original ticket.
- [ ]  This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ]  This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ]  This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ]  This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ]  This ticket conforms to the PRD associated with this part of ProcessMaker.

[FOUR-10237]: https://processmaker.atlassian.net/browse/FOUR-10237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-10298]: https://processmaker.atlassian.net/browse/FOUR-10298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-258ca47afa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-258ca47afa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-258ca47afa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-258ca47afa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-258ca47afa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-258ca47afa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-258ca47afa.eng.processmaker.net

**Comment by mcraeteisha** [comment]
@ryancooley Please disregard the failing SonarQube Quality Gate. The duplicated code that is causing the Quality Gate to fail is required.

**Review by estebangallego — APPROVED** [review]
Approved

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-258ca47afa.eng.processmaker.net

**Pull request merged**
