### PR TITLE
feature/FOUR-18118: [FALL] UI Improvements Fall

### PR DESCRIPTION
**Pull request by pmPaulis**
## Issue & Reproduction Steps
**PRD**
https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3583574017/UI+Improvements+Fall 

**FIGMA**
https://www.figma.com/design/Jfl3HAOx28TVHMl7cHJNIP/Fall-2024?node-id=719-6472&t=OBeO86xMPAx5mOQr-0 

## Solution
- Display Asset Tables in Descending Order
- Update the Behaivor in Launchpad Browser panel
- Update the Behaivor in Case Browser panel

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-18118

## PR Related
https://github.com/ProcessMaker/package-data-sources/pull/372
https://github.com/ProcessMaker/package-ai/pull/297
https://github.com/ProcessMaker/package-decision-engine/pull/143

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:package-ai:feature/FOUR-18118
ci:package-decision-engine:feature/FOUR-18118
ci:package-data-sources:feature/FOUR-18118

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a754e53018.engk8s.processmaker.net

**Review by fagubla — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a754e53018.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a754e53018.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a754e53018.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a754e53018.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a754e53018.engk8s.processmaker.net

**Pull request merged**
