### PR TITLE
4.1 to 4.2 batch 1

### PR DESCRIPTION
**Pull request by nolanpro**
This batch contains the following fixes from 4.1 to 4.2

Ticket # | Link
-- | --
190 | http://tickets.pm4overflow.com/tickets/190
514 | http://tickets.pm4overflow.com/tickets/514
622 | http://tickets.pm4overflow.com/tickets/622
300 | http://tickets.pm4overflow.com/tickets/300
487 | http://tickets.pm4overflow.com/tickets/487

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-1-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-1-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-1-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-1-processmaker.ci.processmaker.net

**Review by runyan-co — APPROVED** [review]
All below tickets for this PR were tested and passed. 

Ticket # | Link
-- | --
190 | http://tickets.pm4overflow.com/tickets/190
514 | http://tickets.pm4overflow.com/tickets/514
622 | http://tickets.pm4overflow.com/tickets/622
300 | http://tickets.pm4overflow.com/tickets/300
487 | http://tickets.pm4overflow.com/tickets/487

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-1-processmaker.ci.processmaker.net

**Pull request merged**
