### PR TITLE
Migrate from Laravel Mix to Vite

### PR DESCRIPTION
**Pull request by nolanpro**
This pull request includes changes for migrating from Laravel Mix to Vite outlined in [Migration Guide](https://github.com/laravel/vite-plugin/blob/main/UPGRADE.md#migrating-from-laravel-mix-to-vite) and automated by the [Vite Converter](https://laravelshift.com/convert-laravel-mix-to-vite).

**Before merging**, you need to:

- Checkout the `shift-101899` branch
- Run `composer update`
- Run `npm install`
- Review **all** comments for additional changes 
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

Please send your feedback to shift@laravelshift.com or share the good vibes on [Twitter](https://twitter.com/laravelshift).

ci:next
.

### CODE REVIEW

**Comment by nolanpro** [comment]
:warning: Shift detected you are using Vue. As such, Vite recommends importing your CSS from your JavaScript entry point. This will improve your development experience by avoiding flashes of unstyled content during hot reloading.

Shift removed your CSS entry point from your Vite configuration. However, you will need to import this CSS in your JavaScript entry point.

**Comment by nolanpro** [comment]
:information_source: Laravel renamed the environment variables used by Mix to use a `VITE_` prefix, instead of `MIX_`. While Shift automated this change throughout your code, you should check for any additional references which may not be included in your Git repository.

**Comment by nolanpro** [comment]
:information_source: Vite requires JavaScript files containing JSX to have a `.jsx` file extension. Shift did not detect any JSX in files with a `.js` extension under the `resources` folder. However, if you are using JSX, be sure the files have a `.jsx` extension.

**Comment by nolanpro** [comment]
:warning: Shift detected you may be using the tilde (`~`) prefix to import CSS or JavaScript. You may try to add an [alias for the `~`](https://github.com/vitejs/vite/issues/5764#issuecomment-982407332) to your Vite configuration. Alternatively, you may update these imports to use an absolute reference or `@` alias.

**Comment by nolanpro** [comment]
:information_source: The new `@vite` Blade directive outputs `<script>` tags with the `type="module"` attribute. This attribute implicitly _defers_ the script. This is a difference from Laravel Mix which may change the execution order of the JavaScript on your page.

If you experience JavaScript errors relating to undefined references, you may need to reorder your scripts or add the `defer` attribute to any inline `<script>` blocks on your page.

**Comment by nolanpro** [comment]
:alembic: This Shift is still being refined. **Please report any issues or suggestions** to [shift@laravelshift.com](mailto:shift@laravelshift.com). Your feedback is what helps improve the experience for everyone.

**Comment by josechirivella** [comment]
Closing this one out since it has become out of date

**Pull request closed without merging**
