### PR TITLE
Error on screen, when PMQL query has non-existent data

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
Fixed [FOUR-2784](https://processmaker.atlassian.net/browse/FOUR-2784)

- add throw exception if participant not exists

### CODE REVIEW

**Review by ryancooley — CHANGES_REQUESTED** [review]
@marcoAntonioNina Looks good but we need to add the string `The specified participant username does not exist.` to the en.json translation file.

**Review by ryancooley — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2784-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2784-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2784-processmaker.ci.processmaker.net

**Pull request merged**
