### PR TITLE
FOUR-10641 Automated Asset Quick Create screen type selection and bug fixes

### PR DESCRIPTION
**Pull request by josechirivella**
## Solution
- Filtering on opening the modal to filter by screen type
- Cleaned a little bit the code
- Added a prop to the `ModelerAssetQuickCreate` to send the screen-type
- Created enums to filter by ScreenType and/or Asset Types

## Related Tickets & Packages

https://processmaker.atlassian.net/browse/FOUR-10641
https://processmaker.atlassian.net/browse/FOUR-10755
https://processmaker.atlassian.net/browse/FOUR-10988

ci:deploy
ci:next

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-bef3d76eed.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-bef3d76eed.eng.processmaker.net

**Review by rodriquelca — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-bef3d76eed.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-bef3d76eed.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-bef3d76eed.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-bef3d76eed.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-bef3d76eed.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-bef3d76eed.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-bef3d76eed.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-bef3d76eed.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-bef3d76eed.eng.processmaker.net

**Pull request merged**
