### PR TITLE
feature/FOUR-13974: The background color Designer is not the same as figma

### PR DESCRIPTION
**Pull request by luNunezProcessmaker**
## Issue & Reproduction Steps
The background color Designer is not the same as figma

The color of icons search and open in Designer are not the same as figma
Icons: search and open
image-20240201-141929

Filter by type is not the same as figma
image-20240201-142748

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-13974

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy

### CODE REVIEW

**Review by fagubla — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-cc23304406.engk8s.processmaker.net

**Comment by pmPaulis** [comment]
@luNunezProcessmaker 
Please add a border-radius like figma
image
Currently does not have this border 
image

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-cc23304406.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-cc23304406.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-cc23304406.engk8s.processmaker.net

**Review by fagubla — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-cc23304406.engk8s.processmaker.net

**Pull request merged**
