### PR TITLE
4.1 to 4.2 batch 2

### PR DESCRIPTION
**Pull request by nolanpro**
This batch contains the following fixes from 4.1 to 4.2

Ticket # | Link
-- | --
515 | http://tickets.pm4overflow.com/tickets/515
557 | http://tickets.pm4overflow.com/tickets/557
357 | http://tickets.pm4overflow.com/tickets/357
172 | http://tickets.pm4overflow.com/tickets/172
359 | http://tickets.pm4overflow.com/tickets/359
606 | http://tickets.pm4overflow.com/tickets/606
499 | http://tickets.pm4overflow.com/tickets/499
615 | http://tickets.pm4overflow.com/tickets/615
331 | http://tickets.pm4overflow.com/tickets/331

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-2-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-2-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-2-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-2-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-2-processmaker.ci.processmaker.net

**Review by runyan-co — APPROVED** [review]
Reviewed, tested, and approved.

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-2-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-2-processmaker.ci.processmaker.net

**Pull request merged**
