### PR TITLE
FOUR-15529: [Summer24] Participant (Home) Welcome Screens V2 

### PR DESCRIPTION
**Pull request by pmPaulis**
## Issue & Reproduction Steps
Introducing "Welcome Screens" can streamline the onboarding process.
Welcome Screens provide a structured introduction to the product or service.
They guide users through key features and functionalities, ensuring a smoother start.

**PRD:** https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3337584641/Welcome+Screens+V2

## Solution
**My Request Items Show Participation and Initiations:**
This feature enhances the "My Request" section to display requests in which the user has participated as well as those they have initiated. 
It provides a comprehensive view of the user's involvement in requests, whether they've initiated them or joined them later.
Users can easily track the progress and status of requests they're actively involved in, regardless of whether they initiated them or joined as participants.

**Include Self-Service in Welcome Screens:**
This feature integrates self-service options into the Welcome Screens of the platform.
Users are greeted with helpful self-service resources and guides immediately upon logging in or accessing the Welcome Screens.
It empowers users to troubleshoot common issues, find answers to frequently asked questions, or access self-service tools and resources without needing to navigate through multiple menus or sections.

**Include Case Title in Welcome Screens My Tasks:**
With this feature, the Case Title is included alongside tasks in the "My Tasks" section of the Welcome Screens.
Users can quickly identify the associated case for each task without having to navigate to separate sections or search for related information.
It improves task management and clarity by providing context directly within the "My Tasks" view.

**Include Case Title in Welcome Screens My Request:**
This feature adds the Case Title to the "My Request" section of the Welcome Screens.
Users can easily identify which case each task is associated with, facilitating better organization and prioritization.
It streamlines task management by providing essential context within the task list itself.

**Include Priority Option in Welcome Screens Tasks:**
This feature introduces a priority option within the tasks displayed on the Welcome Screens.
Users can designate the priority level for each task directly from the Welcome Screens interface.
It enables users to prioritize their tasks effectively and ensures that important tasks receive appropriate attention and action.

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-15531
- https://processmaker.atlassian.net/browse/FOUR-15531
- https://processmaker.atlassian.net/browse/FOUR-15532
- https://processmaker.atlassian.net/browse/FOUR-15533
- https://processmaker.atlassian.net/browse/FOUR-15534
- https://processmaker.atlassian.net/browse/FOUR-15535
- https://processmaker.atlassian.net/browse/FOUR-15536

## PR Related
https://github.com/ProcessMaker/screen-builder/pull/1594
https://github.com/ProcessMaker/package-dynamic-ui/pull/143

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy
ci:screen-builder:feature/FOUR-15529
ci:package-dynamic-ui/feature/FOUR-15529

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-d407f10cd2.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-d407f10cd2.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-d407f10cd2.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-d407f10cd2.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-d407f10cd2.engk8s.processmaker.net

**Review by fagubla — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-d407f10cd2.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-d407f10cd2.engk8s.processmaker.net

**Pull request merged**
