### PR TITLE
Add skip navigation link

### PR DESCRIPTION
**Pull request by caleeli**
Resolves: https://processmaker.atlassian.net/browse/FOUR-2262

Based on the article [Skip Navigation](https://webaim.org/techniques/skipnav/)

Show a first link at the begining of the page to send the user to the main content.

_**Note**: I've added a `tabindex="1"` to the first link because there are some other elements in the page (like the [x] button of the multiselect controls) that have a `tabindex="1"` that were always getting the first tab_

https://user-images.githubusercontent.com/8028650/124190563-7b143600-da90-11eb-8721-1b8b1f24962e.mp4

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2262-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2262-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2262-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2262-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2262-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2262-processmaker.ci.processmaker.net

**Review by ryancooley — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2262-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2262-processmaker.ci.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2262-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Pull request merged**
