### PR TITLE
Maintain anonymous user assignment when exporting/importing

### PR DESCRIPTION
**Pull request by nolanpro**
Fixes https://processmaker.atlassian.net/browse/FOUR-2844

Turns out the issue was in core, not the web entry package

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2844-processmaker.ci.processmaker.net

**Review by caleeli — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2844-processmaker.ci.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2844-processmaker.ci.processmaker.net

**Pull request merged**
