### PR TITLE
FOUR-18064 Encrypted Field in the Screen Builder

### PR DESCRIPTION
**Pull request by julceslauhub**
## Issue & Reproduction Steps
Describe the issue this ticket solves and describe how to reproduce the issue (please attach any fixtures used to reproduce the issue).

## Solution
Implemented new attribute for "line input" fields called "Encrypted"

## How to Test
- Implemented new attribute for "line input" fields called "Encrypted"
- When this new attribute is enabled the designer can assigne users and/or groups
- These users/groups can encrypt/decrypt data
- When the field is rendered a new button will be displayed
- This buttons display the labels "Conceal" or "Reveal" depending the data status
- The first time when the data was not previously conceladed the data is displayed plain
- After click in "Conceal" data is encrypted and an UUID is returned
- This UUID is stored in the request data
- When the data is already concealed the "Reveal" label is displayed in the button
- Whe users clicks in the button the data is decrypted

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-18064

## Code Review Checklist
- [x] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [x] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [x] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [x] This solution fixes the bug reported in the original ticket.
- [x] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [x] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [x] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [x] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [x] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:screen-builder:feature/FOUR-18064
ci:deploy

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ac00108b31.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ac00108b31.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ac00108b31.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ac00108b31.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ac00108b31.engk8s.processmaker.net

**Review by caleeli — APPROVED** [review]

**Pull request merged**
