### PR TITLE
4.1 to 4.2 batch 3

### PR DESCRIPTION
**Pull request by nolanpro**
This batch contains the following fixes from 4.1 to 4.2

Ticket # | Link
-- | --
584 | http://tickets.pm4overflow.com/tickets/584
554 | http://tickets.pm4overflow.com/tickets/554
510 | http://tickets.pm4overflow.com/tickets/510
498 | http://tickets.pm4overflow.com/tickets/498
163 | http://tickets.pm4overflow.com/tickets/163
182 | http://tickets.pm4overflow.com/tickets/182
518 | http://tickets.pm4overflow.com/tickets/518
488 | http://tickets.pm4overflow.com/tickets/488
336 | http://tickets.pm4overflow.com/tickets/336
197 | http://tickets.pm4overflow.com/tickets/197
501 | http://tickets.pm4overflow.com/tickets/501

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-3-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-3-processmaker.ci.processmaker.net

**Review by eiresendez — APPROVED** [review]
Everything works as expected

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-to-4-2-batch-3-processmaker.ci.processmaker.net

**Pull request merged**
