### PR TITLE
multi-select does not display information

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
Fixes [FOUR-3627](https://processmaker.atlassian.net/browse/FOUR-3627)

- add aria-label to dropdwon multiselect  with event open

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3627-processmaker.ci.processmaker.net

**Review by nolanpro — CHANGES_REQUESTED** [review]
@marcoAntonioNina The aria-label needs to be the actual text read to the user, not a reference.

For example, in import.blade.php, the user multiselect should be
```
<multiselect :aria-label="$t(item.prefix) + ' ' + item.name + ' ' + $t(item.suffix)"
```

You can also remove the <label> since it's hidden

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3627-processmaker.ci.processmaker.net

**Comment by marcoAntonioNina** [comment]
resolved comments

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3627-processmaker.ci.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3627-processmaker.ci.processmaker.net

**Pull request merged**
