### PR TITLE
feature/FOUR-9531: IT5 SSO Login Flexibility

### PR DESCRIPTION
**Pull request by pmPaulis**
## Issue & Reproduction Steps
This is a feature defined in the document: https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3158966273/SSO+Login+Improvements

## Stories
Logging in with local credentials bypassing SSO authentication with Standard Login disabled

As a ProcessMaker Administrator/Super admin, I want to be able to logging in with local credentials bypassing SSO authentication with Standard Login disabled. So I can log into ProcessMaker to troubleshoot SSO configuration when/if it fails

## How to Test

- Login to ProcessMaker as an Admin
- Settings
- Select SSO View
- Disable the use Default SSO selecting ProcessMaker

## Related Tickets & Packages
- [FOUR-9531](https://processmaker.atlassian.net/browse/FOUR-9531)
- [FOUR-8501](https://processmaker.atlassian.net/browse/FOUR-8501)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

## Environment Fall
ci:deploy
ci:next
ci:package-auth:feature/FOUR-9531

[FOUR-9530]: https://processmaker.atlassian.net/browse/FOUR-9530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FOUR-9531]: https://processmaker.atlassian.net/browse/FOUR-9531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-8501]: https://processmaker.atlassian.net/browse/FOUR-8501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-fff0f36e2c.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-fff0f36e2c.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-fff0f36e2c.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-fff0f36e2c.eng.processmaker.net

**Review by fagubla — APPROVED** [review]

**Comment by pablobarrososso** [comment]
ci:deploy
ci:modeler:summer-2023-2
ci:package-versions:develop
ci:package-process-optimization:develop

**Comment by pablobarrososso** [comment]
ci:deploy
ci:next
ci:package-auth:feature/FOUR-9531

**Pull request merged**
