### PR TITLE
ticket 517: Boundary timer events getting wrong bpmn version

### PR DESCRIPTION
**Pull request by danloa**
Fixes bug found in [http://tickets.pm4overflow.com/tickets/517](http://tickets.pm4overflow.com/tickets/517)

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-517-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-517-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-517-processmaker.ci.processmaker.net

**Review by caleeli — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-517-processmaker.ci.processmaker.net

**Pull request merged**
