### PR TITLE
QA Observation Bugfix/FOUR-12877: Error when create a Script task from Designer

### PR DESCRIPTION
**Pull request by CarliPinell**
## Solution
- The missing getAdminUser function was added and Error Message is not on console anymore.

## How to Test
TEST 1
- Open NEW Script from Designer Page in Assets section
- Create and Save Script, after saving Modal Window Should hide.

TEST 2

- Create New Project
- In MY PROJECTS section OPEN a project
- Add an ASSET
- Select SCRIPT
- Create and Save Script, after saving Modal Window Should hide.

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-12877

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.
ci:deploy
ci:next

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8d9521102d.eng.processmaker.net

**Review by fagubla — APPROVED** [review]

**Review by fagubla — APPROVED** [review]

**Review by pmPaulis — APPROVED** [review]

**Comment by pmPaulis** [comment]
After to save the modal is not closed:
image

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8d9521102d.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8d9521102d.eng.processmaker.net

**Pull request merged**
