### PR TITLE
When creating a screen or script from the task in the modeler, the modal does not direct you to edit it, it remains open

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
## Issue & Reproduction Steps
There was no longer a redirect to the page when creating a screen.

## Solution
- Putting the changes back.

## How to Test
Log in
Create a process
Go to Designer tab
Click on +Process button
Select Build Your Own
Fill name and description
Click on save button

Scenarios:

Form task
    Add form task to modeler
    Click on form task control
    Click on Create a new screen link
    Fill name and description
    Select Form in screen type
    Click on save button

Manual Task
    Add form task to modeler
    Click on form task control
    Change to Manual task
    Click on Create a new screen link
    Fill name and description
    Click on save button

Script task
    Add form task to modeler
    Click on form task control
    Change to Script task
    Click on Create a new scriptlink
    Fill name and description
    Select a language
    Click on save button

## Related Tickets & Packages
- [FOUR-12900](https://processmaker.atlassian.net/browse/FOUR-12900)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy

[FOUR-12900]: https://processmaker.atlassian.net/browse/FOUR-12900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by agustinbusso — APPROVED** [review]

**Review by CarliPinell — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-0638a10393.engk8s.processmaker.net

**Comment by pmPaulis** [comment]
@marcoAntonioNina 
I tested in the build  https://ci-0638a10393.engk8s.processmaker.net/
A found some behaviour to review:

https://github.com/ProcessMaker/processmaker/assets/42388723/2428ef8a-efb2-4bc8-befc-00ecca81cfb7
Project-> asset -> script (not list the languages and the button save does not work)
image
Modeler -> Script (the button save does not work)
image

image

Regards,

**Comment by marcoAntonioNina** [comment]
@pmPaulis Apparently there were problems generating the build, but it has been tested locally and there are no such problems.

**Comment by pmPaulis** [comment]
I tested in my locally and it works.

https://github.com/ProcessMaker/processmaker/assets/42388723/4910ce8a-f365-4246-8cc2-8c82ac145cb7

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-0638a10393.engk8s.processmaker.net

**Review by pmPaulis — APPROVED** [review]

**Comment by pmPaulis** [comment]
In the last build this is working fine:
image

**Pull request merged**
