### PR TITLE
FOUR-14560 | Unable to Preview Templates in Screen Template Listings

### PR DESCRIPTION
**Pull request by mcraeteisha**
# Issue
Ticket: [FOUR-14560](https://processmaker.atlassian.net/browse/FOUR-14560)
The option to preview a template is missing from the My Templates and Public Templates listings. Users should be able to preview templates from the listing tabs.

# Solution
- Update Ellipsis Menu to appear as a tooltip.
- Add templatePreviewMixin for Preview functionality in the tooltip.
- Create TemplatePreviewContainer component to display the Template Preview.

# How to Test
1. Go to branch `observation/FOUR-14560` in `processmaker`.
2. Go to Designer → Screens. Ensure that you have Screen Templates created.
3. Go to the My Templates tab and hover over a template. 
	- A tooltip should appear with the Ellipsis Menu.
4. Click on the eye icon in the tooltip.
5. A template preview should appear.
	- Ensure that the template details, including any CSS, are accurate.
6. Ensure that the other Ellipsis Menu actions under 'Options' behave as expected.
7. Complete the same steps for templates in the Public Templates tab.

ci:next
ci:deploy

# Code Review Checklist

- [ ]  I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ]  This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ]  This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ]  This solution fixes the bug reported in the original ticket.
- [ ]  This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ]  This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ]  This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ]  This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ]  This ticket conforms to the PRD associated with this part of ProcessMaker.

[FOUR-14560]: https://processmaker.atlassian.net/browse/FOUR-14560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a157b570c2.engk8s.processmaker.net

**Review by estebangallego — APPROVED** [review]
Works as expected

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a157b570c2.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a157b570c2.engk8s.processmaker.net

**Pull request merged**
