### PR TITLE
Center action column tooltips on hover

### PR DESCRIPTION
**Pull request by sanjacornelius**
**Jira Ticket**

https://processmaker.atlassian.net/browse/FOUR-2948

<h2>Changes</h2>

- Issue resides within the bootstrap-vue library. Used this worked around to fix.

https://github.com/bootstrap-vue/bootstrap-vue/issues/5277
https://github.com/bootstrap-vue/bootstrap-vue/issues/1732#issuecomment-678806650

**Video**

https://www.loom.com/share/c2a58a4385074c989432353a715ad990

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2948-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2948-processmaker.ci.processmaker.net

**Review by GooseCoder — APPROVED** [review]
changes are passing the pipelines, lgtm

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2948-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-1-processmaker.ci.processmaker.net

**Pull request merged**
