### PR TITLE
Add inactive indicator to users and groups

### PR DESCRIPTION
**Pull request by nolanpro**
Fixes http://tickets.pm4overflow.com/tickets/501

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-501-processmaker.ci.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-501-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-501-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Pull request merged**
