### PR TITLE
[DO NOT MERGE] Screen Templates Test Server

### PR DESCRIPTION
**Pull request by sanjacornelius**
Test:

ci:next
ci:package-files:task/FOUR-15289
ci:deploy
.

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a7fa9ea052.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a7fa9ea052.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a7fa9ea052.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a7fa9ea052.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a7fa9ea052.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a7fa9ea052.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a7fa9ea052.engk8s.processmaker.net

**Comment by sanjacornelius** [comment]
Closing no longer needed

**Pull request closed without merging**
