### PR TITLE
If user assignment is not valid reassign to Process Manager

### PR DESCRIPTION
**Pull request by caleeli**

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-674-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-674-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-674-processmaker.ci.processmaker.net

**Review by velkymx — COMMENTED** [review]
Code looks good. Checking the testing server

**Comment by velkymx** [comment]
Screen Shot 2021-09-07 at 3 48 33 PM

**Review by velkymx — APPROVED** [review]
Tested process works as expected

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-674-processmaker.ci.processmaker.net

**Pull request merged**
