### PR TITLE
Ticket #708: Merge Customize UI and Dynamic UI

### PR DESCRIPTION
**Pull request by ryancooley**
## Changes
- Adds support for Dynamic UI package to add extra tabs to Customize UI page

## Requirements
- https://github.com/ProcessMaker/package-dynamic-ui/pull/45

## Tickets
- http://tickets.pm4overflow.com/tickets/708

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-708-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-708-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-708-processmaker.ci.processmaker.net

**Review by sanjacornelius — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-708-processmaker.ci.processmaker.net

**Pull request merged**
