### PR TITLE
FOUR-3044: The task does not reach the self service tray

### PR DESCRIPTION
**Pull request by danloa**
Fixes FOUR-3044, FOUR-3030, FOUR-3052

### CODE REVIEW

**Review by caleeli — COMMENTED** [review]
Please add <userTask> to the list of self services

**Review by caleeli — APPROVED** [review]

**Review by sanjacornelius — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3044-b-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3044-b-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-17-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3044-b-processmaker.ci.processmaker.net

**Pull request merged**
