### PR TITLE
Bugfix/FOUR-16575: Bugfix/FOUR-16575: Getting OOM Memory Failures when Calling Tasks API Endpoint

### PR DESCRIPTION
**Pull request by agustinbusso**
**Fixes**
https://processmaker.atlassian.net/browse/FOUR-16575

ci:next

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-309fcb93b2.engk8s.processmaker.net

**Comment by nolanpro** [comment]
@agustinbusso @caleeli I would consider using this exclude scope: https://stackoverflow.com/questions/23612221/how-to-exclude-certains-columns-while-using-eloquent/56425794#56425794

You can drop it right into ProcessMaker/Models/ProcessMakerModel.php and it should work everywhere.

Also, process_reqests also has the `data` field, and processes also has some big columns, so you should exclude them when eager loading too

```
        $query = ProcessRequestToken::exclude(['data'])->with([
            'processRequest' => fn($q) => $q->exclude(['data']),
            'process' => fn($q) => $q->exclude(['svg', 'bpmn', 'warnings']),
            'user',
            'draft'
        ]);
```

You'll need to remove `scopeExclude` from Screen.php since this replaces it.

**Comment by caleeli** [comment]
The following scenarios are being tested:

- [ ] Test the Tasks table
- [ ] Test the endpoint as reported in the ticket
- [ ] Search by data.fields E.g. data.Year="2024"
- [ ] Filter by different columns
- [ ] Add data columns like data.Year
- [ ] Create a Task Saved Search that includes different columns and data fields

**Comment by caleeli** [comment]
SEARCH BY DATA
image

Filter and sort by data column
image

**Review by caleeli — APPROVED** [review]

**Pull request merged**
