### PR TITLE
Laravel 10 Upgrade

### PR DESCRIPTION
**Pull request by nolanpro**
## Issue & Reproduction Steps
See https://processmaker.atlassian.net/browse/FOUR-9714

Laravel upgrade from 8 to 9 to 10

## Solution
- Upgrade core Laravel packages and dependencies
- Make required changes to core and PM packages
- Use php 8.2

## How to Test
- Use php 8.2
- Smoke test the app
- List of specific changes to test TBD

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-7194

Packages
https://github.com/ProcessMaker/connector-docusign/pull/36
https://github.com/ProcessMaker/connector-send-email/pull/263
https://github.com/ProcessMaker/docker-executor-node-ssr/pull/9
https://github.com/ProcessMaker/package-actions-by-email/pull/118
https://github.com/ProcessMaker/package-collections/pull/360
https://github.com/ProcessMaker/package-data-sources/pull/314
https://github.com/ProcessMaker/package-decision-engine/pull/53
https://github.com/ProcessMaker/package-pm-blocks/pull/84
https://github.com/ProcessMaker/package-savedsearch/pull/378
https://github.com/ProcessMaker/package-sentry/pull/16
https://github.com/ProcessMaker/package-translations/pull/60
https://github.com/ProcessMaker/package-versions/pull/69
https://github.com/ProcessMaker/package-vocabularies/pull/82
https://github.com/ProcessMaker/package-webentry/pull/213
https://github.com/ProcessMaker/pmql/pull/35

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:connector-send-email:feature/FOUR-9714
ci:docker-executor-node-ssr:feature/FOUR-9714
ci:package-webentry:feature/FOUR-9714
ci:package-savedsearch:feature/FOUR-9714
ci:package-data-sources:feature/FOUR-9714
ci:package-sentry:feature/FOUR-9714
ci:package-translations:feature/FOUR-9714
ci:pmql:feature/FOUR-9714
ci:package-pm-blocks:feature/FOUR-9714
ci:package-actions-by-email:feature/FOUR-9714
ci:package-collections:feature/FOUR-9714
ci:connector-docusign:feature/FOUR-9714
ci:package-decision-engine:feature/FOUR-9714
ci:package-vocabularies:feature/FOUR-9714
ci:package-versions:feature/FOUR-9714

ci:deploy
..

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0dc9988931.eng.processmaker.net

**Review by gustavobascope — APPROVED** [review]
I made a smoke test of the main functionalities

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0dc9988931.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0dc9988931.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0dc9988931.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0dc9988931.eng.processmaker.net

**Pull request merged**
