### PR TITLE
FOUR-2921: Unable to filter the list in a Saved Search chart

### PR DESCRIPTION
**Pull request by danloa**
Fixes [https://processmaker.atlassian.net/browse/FOUR-2921](https://processmaker.atlassian.net/browse/FOUR-2921)

Added filtering by id and dates of process requests, and process request tokens.

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2921-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2921-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2921-processmaker.ci.processmaker.net

**Review by caleeli — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2921-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Pull request merged**
