### PR TITLE
FOUR-3295: Improve watcher outbound configuration helper text

### PR DESCRIPTION
**Pull request by danloa**
As part of fixes to [https://processmaker.atlassian.net/browse/FOUR-3295](https://processmaker.atlassian.net/browse/FOUR-3295)

### CODE REVIEW

**Review by nolanpro — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3295-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3295-processmaker.ci.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3295-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Pull request merged**
