### PR TITLE
Implement Preview Template Feature in Create New Screen Modal

### PR DESCRIPTION
**Pull request by sanjacornelius**
This PR implements the 'Preview Template' functionality within the Create New Screen modal. Selecting 'Preview Template' displays an image viewer for the thumbnails uploaded to a template. Additionally, users can preview the template's custom CSS code.

## Solution

- Added frontend components and UI elements to support template preview functionality.
- Integrated image viewer for thumbnail previews.
- Implemented logic to display custom CSS code preview within the modal.

## How to Test

1. Open the Create New Screen modal.
2. Upload thumbnails for the template.
3. Click on the 'Preview Template' option.
4. Verify that the uploaded thumbnails are displayed in the image viewer.
5. Check if the custom CSS code is properly rendered in the preview section.
6. Optionally, make changes to the thumbnails or CSS code and observe the live preview.

## Related Tickets & Packages

[FOUR-13496](https://processmaker.atlassian.net/browse/FOUR-13496)

ci:next
ci:deploy

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

[FOUR-13496]: https://processmaker.atlassian.net/browse/FOUR-13496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-945954b2c9.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-945954b2c9.engk8s.processmaker.net

**Review by mcraeteisha — APPROVED** [review]
Approved!

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-945954b2c9.engk8s.processmaker.net

**Pull request merged**
