### PR TITLE
ticket 622: DocumentationTest Failing

### PR DESCRIPTION
**Pull request by danloa**
Resolves: [http://tickets.pm4overflow.com/tickets/622](http://tickets.pm4overflow.com/tickets/622)

### CODE REVIEW

**Review by boliviacoca — APPROVED** [review]

**Review by marcoAntonioNina — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-622-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-622-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-622-processmaker.ci.processmaker.net

**Pull request merged**
