### PR TITLE
Implement Importing of Wizard Template

### PR DESCRIPTION
**Pull request by sanjacornelius**
This PR introduces the following functionalities related to Guided Templates:

1. Importing of Wizard Template:

- Upon completion of the helper process, the wizard template is imported.
- If existing assets from the template are present, the user is redirected to handle these assets.
- Upon completion, the user is redirected to the newly created process launchpad.

2. Rerun Wizard Capability:

- Enabled the capability to rerun the wizard helper process from the newly created process launchpad.

3. Nightly Sync of Wizard Templates:

- Enabled the nightly sync of wizard templates.

## How to Test

1. Ensure you have access to a local development environment.
2. Run php artisan processmaker:sync-wizard-templates.
3. Navigate to 'Processes > Guided Templates'.
4. Select a Guided Template.
5. Select 'Use Now'.
6. Complete the process configuration.
7. Upon completion:

-  If there are existing assets from that template, ensure you are redirected to the existing assets page to handle those assets. After completing, ensure redirection to the newly created process launchpad.

- If there are no existing assets, ensure redirection to the newly created process launchpad.

8. Within the process launchpad, ensure the 'Re-run Wizard' link is visible.
9. Select the link.
10. Ensure the helper process is opened in a modal.

## Related Tickets & Packages
Resolves:
- [FOUR-12181](https://processmaker.atlassian.net/browse/FOUR-12181)
- [FOUR-11769](https://processmaker.atlassian.net/browse/FOUR-11769)

ci:next
ci:deploy

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

[FOUR-12181]: https://processmaker.atlassian.net/browse/FOUR-12181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-e5f5fe254c.eng.processmaker.net

**Review by mcraeteisha — APPROVED** [review]
Approved!

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-e5f5fe254c.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-e5f5fe254c.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-e5f5fe254c.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-e5f5fe254c.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-e5f5fe254c.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-e5f5fe254c.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-e5f5fe254c.eng.processmaker.net

**Pull request merged**
