### PR TITLE
FOUR-6601: Refactor settings

### PR DESCRIPTION
**Pull request by runyan-co**
## Environment Setup
- Set core to this PR's branch: [refactor/FOUR-6601](https://github.com/ProcessMaker/processmaker/tree/refactor/FOUR-6601)
- Set connector-send-email to [refactor/FOUR-6601](https://github.com/ProcessMaker/connector-send-email/pull/217)
- Set package-actions-by-email to [refactor/FOUR-6601](https://github.com/ProcessMaker/package-actions-by-email/pull/83/files)
- Set package-collections [refactor/FOUR-6601](https://github.com/ProcessMaker/package-collections/pull/325)
- Set package-auth to [refactor/FOUR-6601](https://github.com/ProcessMaker/package-auth/pull/66)
- Set package-ellucian-ethos to [refactor/FOUR-6601](https://github.com/ProcessMaker/package-ellucian-ethos/pull/72)

## Issue & Reproduction Steps
We used to utilize a tagged Redis cache to store settings to reduce the number of queries to the database every time the app is loaded. Over time, we've noticed the cache actually creates too many network calls to Redis (it makes a network call everytime a cached setting is called) and it uses a lot more memory by each PHP process. We also had a `settings()` function helper which complicates things as all settings were also in the global app config (accessed using the `config()` function helper).

This PR refactors the settings so they can be easily accessed through the global app configuration. This will reduce the duplicative nature of the `settings()` helper and simplify the app config caching process. 

## Solution
The `SettingsServiceProvider` loads all settings from the database and binds the key and config values into the app’s global configuration. If the app configuration is cached when a setting is saved or updated, the config will automatically be cleared and re-cached. Horizon will also be restarted when the configuration is re-cached to ensure it picks up the updated config values.

## Refactoring settings usage in packages
Multiple packages implement and use settings, however this refactor deprecates the `settings()`, `flush_settings()`, and the `cache_settings()` function helpers. There are also other changes which need to be made to specific place in the below packages to ensure the settings are correctly implemented.

## How to Test
Extensive testing will be required to ensure all PRs cover all use cases of settings, ensuring they are updated (even when the configuration is cached).

## Related Tickets & Packages
- [PR for connector-send-email](https://github.com/ProcessMaker/connector-send-email/pull/216)
- [PR for package-collections](https://github.com/ProcessMaker/package-collections/pull/323)
- [PR for package-auth](https://github.com/ProcessMaker/package-auth/pull/65)
- [PR for package-ellucian-ethos](https://github.com/ProcessMaker/package-ellucian-ethos/pull/71)
- [Ticket FOUR-6601](https://processmaker.atlassian.net/browse/FOUR-6601)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Review by agustinbusso — COMMENTED** [review]
For saved search I just did a test, and it seems the settings still cached, please watch the following video @runyan-co

https://user-images.githubusercontent.com/90727999/185627837-cbafd579-9cec-4449-9480-d4912943223d.mov

**Review by agustinbusso — COMMENTED** [review]
Extended properties configuration working correctly:

https://user-images.githubusercontent.com/90727999/185635454-327907fd-ecaa-4a7c-954c-fc20fdf2336b.mov

SSO configuration working correctly:

https://user-images.githubusercontent.com/90727999/185635569-9cb0a7c2-b748-4d34-9a51-a41a20a080c5.mov

**Review by agustinbusso — COMMENTED** [review]
Horizon is terminating constantly after trying to run a process with data connector:

https://user-images.githubusercontent.com/90727999/185635802-fc7351be-1f7c-4e30-9cce-a0311fe915c4.mov


https://user-images.githubusercontent.com/90727999/185635869-ce8cae4d-f979-4917-9750-72fb7d66038a.mov

**Review by agustinbusso — COMMENTED** [review]
ABE seems to be working correctly:

https://user-images.githubusercontent.com/90727999/185659447-5f2a718f-50fb-4a62-b09b-ca94eea80057.mov

**Review by agustinbusso — COMMENTED** [review]
SCIM settings working correctly:

https://user-images.githubusercontent.com/90727999/185694125-72844a57-8868-43eb-89df-f14dca0eb3f4.mov

**Review by agustinbusso — COMMENTED** [review]
SAML settings working correctly:

https://user-images.githubusercontent.com/90727999/185698147-5c234205-43de-4afd-b4fe-1a266d941d8a.mov

**Comment by runyan-co** [comment]
> Details

Hey @agustinbusso, I reviewed your screen recording and it looks like it's working correctly.  Since you're running horizon in the foreground (using `php artisan horizon`), it's sending a shutdown signal to that particular PHP process. In a production environment (or my local dev environment, cause I'm lazy), [supervisor](https://laravel.com/docs/6.x/horizon#deploying-horizon) is usually used to continually spawn new PHP processes (running horizon) as needed.

I went ahead and included my own supervisor ".conf" file below if you want to use it. You'll have to change out the path to artisan in the file and then place it in `/usr/local/etc/supervisor.d`  (or `/opt/homebrew/etc/supervisor.d` for M1 MacBooks) and then restart supervisor (`supervisorctl reread`, `supervisorctl update`, `supervisorctl restart all`).

```
[program:horizon]
process_name=%(program_name)s_%(process_num)02d
command=/opt/homebrew/bin/php /Users/alex/code/processmaker/artisan horizon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=alex
numprocs=1
redirect_stderr=true
stdout_logfile=/Users/alex/logs/%(program_name)s_%(process_num)02d.log
stopwaitsecs=3600
```

**Comment by agustinbusso** [comment]
Saved search send email report working correctly

https://user-images.githubusercontent.com/90727999/186436961-587d4546-57aa-441d-8e1b-6a5fa69b504d.mov

**Comment by agustinbusso** [comment]
Send email from connector working correctly:

https://user-images.githubusercontent.com/90727999/186442480-a39548b9-29c9-4b28-be9d-e73253047428.mov

**Comment by agustinbusso** [comment]
Docusign settings changing correctly:

https://user-images.githubusercontent.com/90727999/186447648-adbd20ea-63b0-4537-b9bb-8a188e95f3ad.mov

**Comment by agustinbusso** [comment]
Test for [FOUR-6599](https://processmaker.atlassian.net/browse/FOUR-6599):
**Send Report of save search is sent without having configurations in the email settings**

Working well, settings are not cached:


https://user-images.githubusercontent.com/90727999/186495947-7eba73da-9892-4fa4-a9df-1f61cc73d7d8.mov


https://user-images.githubusercontent.com/90727999/186495991-33288eb6-866f-482c-9baa-49aa14c25e24.mov

**Review by nolanpro — APPROVED** [review]

**Review by danloa — APPROVED** [review]

**Comment by danloa** [comment]
List of verifications:
Configure email - OK
Test email connector - OK
Configure ABE - OK
Test ABE - OK
Collections - OK
Configure Ethos - OK
Ethos - OK

**Review by ryancooley — APPROVED** [review]

**Pull request merged**
