### PR TITLE
Resolve Loading Screen Issue in My Templates and Public Templates Tabs

### PR DESCRIPTION
**Pull request by sanjacornelius**
## Issue & Reproduction Steps
This PR addresses an issue where the My Template and Public Template tabs consistently display the loading screen on slower networks. This problem arises from the improper implementation of the `apiDataLoading`,` loading`, and `noResults` variables during the component creation, the `fetch` method, and upon receiving a response.

## Solution

- Properly implemented the `apiDataLoading`, `loading`, and `noResults` variables to manage the loading state of the components at various stages.

## How to Test

1. In your browser's network panel, set your connection speed from `No Throttling` to `Slow 3g`.
2. Navigate to the Designer > Screen.
3. Before the page fully loads, select either the My Templates or Public Templates tab.
4. Confirm that the loading screen appears and disappears after a period, indicating successful loading of the templates.

## Related Tickets & Packages
[FOUR-14721](https://processmaker.atlassian.net/browse/FOUR-14721)

ci:next
ci:deploy

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

[FOUR-14721]: https://processmaker.atlassian.net/browse/FOUR-14721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-1bc7616e1f.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-1bc7616e1f.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-1bc7616e1f.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-1bc7616e1f.engk8s.processmaker.net

**Review by mcraeteisha — APPROVED** [review]
Approved!

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-1bc7616e1f.engk8s.processmaker.net

**Pull request merged**
