### PR TITLE
FOUR-8229 Log Unauthorized access attempts

### PR DESCRIPTION
**Pull request by paulosakamoto**
## Issue & Reproduction Steps
Describe the issue this ticket solves and describe how to reproduce the issue (please attach any fixtures used to reproduce the issue).

## How to Test
- Create a user with only requests permissions
- Open the Admin Settings page `/admin/settings`

## Related Tickets & Packages
- [FOUR-8229](https://processmaker.atlassian.net/browse/FOUR-8229)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy

[FOUR-8229]: https://processmaker.atlassian.net/browse/FOUR-8229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-ca09e8dd8a.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-ca09e8dd8a.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-ca09e8dd8a.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-ca09e8dd8a.eng.processmaker.net

**Review by pmPaulis — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-ca09e8dd8a.eng.processmaker.net

**Review by pmPaulis — APPROVED** [review]

**Pull request merged**
