### PR TITLE
Signal Manager List Icons

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
Fixed [FOUR-3249](https://processmaker.atlassian.net/browse/FOUR-3249)

-  Change button delete signal to disabled

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3249-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3249-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3249-processmaker.ci.processmaker.net

**Review by caleeli — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3249-processmaker.ci.processmaker.net

**Pull request merged**
