### PR TITLE
FOUR-19037 Refactor template importing

### PR DESCRIPTION
**Pull request by nolanpro**
## Issue & Reproduction Steps
The Expense Report guided template was taking about 45 seconds to run locally (post to `api/1.0/template/create/process/53`)

## Solution
- Cache Schema lookups
- Refactor Options
- Remove generating manifest (expensive) from every associate categories call
- Prevent duplicate calls, short circuit re-order so expensive calls are last, other basic cleanup.

## How to Test
Sync guided templates and install the expense report (you can skip the HR system). Observe how long it takes to install the process and go the dashboard

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-19037

ci:deploy
ci:next

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Review by estebangallego — APPROVED** [review]
Works as expected!

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-109979e83e.engk8s.processmaker.net

**Comment by boliviacoca** [comment]
In sync with @nolanpro and @ryancooley we added the HOLD label to include https://processmaker.atlassian.net/browse/SCO-25140

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-109979e83e.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-109979e83e.engk8s.processmaker.net

**Pull request merged**
