### PR TITLE
feature/FOUR-9487: IT2 Participant Task Preview Pane

### PR DESCRIPTION
**Pull request by pmPaulis**
## Issue & Reproduction Steps
This is a feature defined in the document: https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3123380270/Participant+Task+Preview+Pane

## Solution
Implement the following user stories:
- As a Request Participant, I want to preview a task assigned to me in order to review it and choosing whether to submit it directly, open it fully, or leave it and navigate away. 
- As a Participant, I want to jump between task and their Preview, without having to close the preview and opening the next one or previous one, so that I can understand my open tasks.

## How to Test

- Create a **process** with some tasks and **screen** related in the task
- Create a **Request**
- Go to the **Task** top menu

## Related Tickets & Packages
- [FOUR-9487](https://processmaker.atlassian.net/browse/FOUR-9487)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

## Enviroment
ci:deploy

[FOUR-9487]: https://processmaker.atlassian.net/browse/FOUR-9487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-2cde79f8e6.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-2cde79f8e6.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-2cde79f8e6.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-2cde79f8e6.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-2cde79f8e6.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-2cde79f8e6.eng.processmaker.net

**Review by luNunezProcessmaker — APPROVED** [review]

**Review by CarliPinell — APPROVED** [review]

**Pull request merged**
