### PR TITLE
Update sanitizer so we can allow some tags from rich text input

### LINKED ISSUE #2043: Rich Text Area
As a user I want to allow my tasks to collect rich text in an textarea control. 

- [x] Add a checkbox with the textarea inspector "Allow Rich Text"
- [x] Enable TinyMCE in the Task View for that textarea

https://github.com/ProcessMaker/vue-form-elements/issues/49

### PR DESCRIPTION
**Pull request by nolanpro**
Fixes #2043 

Moves sanitation middleware functionality to a helper class

Related PRs
- https://github.com/ProcessMaker/vue-form-elements/pull/55
- https://github.com/ProcessMaker/screen-builder/pull/293

### CODE REVIEW

**Comment by ryancooley** [comment]
@PMQABen Can you throw some XSS at this to make sure it's solid before we merge it in?

**Comment by PMQABen** [comment]
Not seeing the option to enable rich text for the Textarea Control. Unsure if I built this improperly on my local machine.

**Comment by velkymx** [comment]
@nolanpro I like where you head is at on this one!

**Comment by PMQABen** [comment]
After it all got merged into develop, I was able to make this work. Kinda. I put `<script>alert(123)</script>` into a Rich Text-enabled textarea, and the variable for the data preview came out like this:

```
{
"a1": "<table class="highlight tab-size js-file-line-container" style="border-spacing: 0px; tab-size: 8; color: #24292e; font-family: -apple-system, system-ui, 'Segoe UI', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px;" data-tab-size="8"> <tbody> <tr> <td id="LC330" class="blob-code blob-code-inner js-file-line" style="padding: 0px 10px; line-height: 20px; position: relative; vertical-align: top; font-family: SFMono-Regular, Consolas, 'Liberation Mono', Menlo, monospace; font-size: 12px; overflow: visible; white-space: pre; overflow-wrap: normal;">&lt;script&gt;alert(123)&lt;/script&gt;</td> </tr> <tr> <td id="L331" class="blob-num js-line-number" style="padding: 0px 10px; color: rgba(27, 31, 35, 0.3); cursor: pointer; font-family: SFMono-Regular, Consolas, 'Liberation Mono', Menlo, monospace; font-size: 12px; line-height: 20px; min-width: 50px; text-align: right; user-select: none; vertical-align: top; white-space: nowrap; width: 50px;" data-line-number="331">&nbsp;</td> </tr> </tbody> </table>"
}
```
Even though HTML code gets processed through the textarea field, it does not get parsed as such when passing it as a variable to a Text Control or a Rich Text Control.

image
image

**Pull request merged**
