### PR TITLE
Loops Update Parallel Multi-Instance

### PR DESCRIPTION
**Pull request by caleeli**
Resolves: http://tickets.pm4overflow.com/tickets/696

This PR includes:
- Add public object `ProcessMaker.modelerExtensions` to publish loop characteristics extensions, so they could be used by extended Service Tasks like email-connector
- Add new MI labels

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-696-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-696-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-696-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-696-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-696-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-696-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-696-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-696-processmaker.ci.processmaker.net

**Review by danloa — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-696-processmaker.ci.processmaker.net

**Pull request merged**
