### PR TITLE
FOUR-12410 Use K8S CICD Pipeline - develop branch

### PR DESCRIPTION
**Pull request by mavalosn**
ci:package-data-sources:FOUR-12410
ci:DATASOURCES_TEST_ENV="Custom Env Var From CI"
ci:modeler:FOUR-12410
ci:screen-builder:FOUR-12410
ci:deploy
..

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-70cf434f7c.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-70cf434f7c.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-70cf434f7c.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-70cf434f7c.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-70cf434f7c.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-70cf434f7c.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-70cf434f7c.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-70cf434f7c.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-70cf434f7c.engk8s.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Pull request merged**
