### PR TITLE
Integrate Gmail SMTP Email Server

### PR DESCRIPTION
**Pull request by sanjacornelius**
## Issue & Reproduction Steps

Ticket: [FOUR-6104](https://processmaker.atlassian.net/browse/FOUR-6104)

As a System Administrator, I want to enable an email server using the Gmail SMTP so that my platform utilizes my preferred and familiar email service

This PR updates the Settings UI based on the [Email Server PRD](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/2761064449/Email+Server+Options+-+Office365+Modern+Auth+and+Gmail+API) specifications as well as adds a new SMTP Authentication Method option allowing users to select either Standard Authentication or Google Authentication.

## Solution

- Remove Pagination
- Update the placement and verbiage of tab buttons
- Update 'Action' icons
- Adds new 'SMTP Authentication Method' UI config
- Adds the 'google' option in the UI for the 'SMTP Authentication Method' Model
- Implements XOAUTH2 for Gmail SMTP
- Adds migrations: `update_ui_in_settings_table` and `add_gmail_smtp_in_settings_table`

## UI Updates

**Before**

Screen Shot 2022-07-14 at 11 07 28 AM
Screen Shot 2022-07-14 at 11 07 39 AM

**After**

Screen Shot 2022-08-02 at 12 41 43 PM

Screen Shot 2022-08-02 at 12 42 35 PM

## How to Test

**Testing UI and Migration**

1. Review the [PRD](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/2761064449/Email+Server+Options+-+Office365+Modern+Auth+and+Gmail+API)
2. Ensure you are on the `develop` branch for both Core and Send Email Connector
3. Ensure the following packages are installed - 
    - Auth Package
    - Send Email Connector [PR](https://github.com/ProcessMaker/connector-send-email/pull/209) `develop`
    - Actions By Email
    - DocuSign Connector
4. Configure a few Email servers with and without SMTP settings
5. Update Core branch `feature/FOUR-6104B` 
6. Update Send Email Connector branch `feature/FOUR-6104B`
7. Reinstall Send Email Connector
4. Run `php artisan migrate`
8. Within the settings tabs ensure UI displays properly as specified in the PRD
   - Buttons are displayed properly
   - Existing Email Servers Configurations display properly
   - Add / Remove Email Servers works as expected
   - Configurations Update as expected. etc...

## Related Tickets & Packages
- Ticket: [FOUR-6104](https://processmaker.atlassian.net/browse/FOUR-6104)
- [Email Server PRD](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/2761064449/Email+Server+Options+-+Office365+Modern+Auth+and+Gmail+API)
- ~~[Send Email PR](https://github.com/ProcessMaker/connector-send-email/pull/209)~~ `feature/FOUR-6104`
- [Send Email NEW PR](https://github.com/ProcessMaker/connector-send-email/pull/211) `feature/FOUR-6104B`

ci:connetor-send-email:feature/FOUR-6104B

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Review by agustinbusso — COMMENTED** [review]
While trying to migrate, I'm having an error in the terminal (previously I created 3 email servers in develop):

Screen Shot 2022-08-03 at 17 38 44

If I remove the third email server created in processmaker settings, and then I try to run again migrate command, it works:

Screen Shot 2022-08-03 at 17 42 23

**Review by agustinbusso — COMMENTED** [review]
### SOLVED
After the issue with the offset and running the migrate command, server 3 and 2 was deleted (and I only remove the server 3). Also while trying to create a new server an error message appears the first time and the if you click again in the button "+ MAIL SERVER" then no error shows and the server are created.

Screen Shot 2022-08-03 at 17 53 47

Screen Shot 2022-08-03 at 17 54 03

**Review by agustinbusso — COMMENTED** [review]
- Remove Pagination **[CORRECT]**

Screen Shot 2022-08-03 at 16 44 41

- Update the placement and verbiage of tab buttons **[CORRECT]**

Screen Shot 2022-08-03 at 16 37 26
Screen Shot 2022-08-03 at 16 37 34
Screen Shot 2022-08-03 at 16 41 18
Screen Shot 2022-08-03 at 16 41 23

- Update 'Action' icons **[CORRECT]**
Screen Shot 2022-08-03 at 16 45 59

- Adds new 'SMTP Authentication Method' UI config **[CORRECT]**
- Adds the 'google' option in the UI for the 'SMTP Authentication Method' Model **[CORRECT]**

https://user-images.githubusercontent.com/90727999/183442797-0d91d8a1-f1c3-453e-8575-cdc0532dbf0a.mov

**Review by agustinbusso — COMMENTED** [review]
After move from develop to the branch feature/FOUR-6104B, and when trying to run `php artisan migrate` in core and `php artisan package-auth:install` for package auth I'm getting a console error. Also if you see, not all the servers configured in develop are showing. Please watch the videos:

**Default email server and email server 1, 2, 3 and 4 configured in develop.**

https://user-images.githubusercontent.com/90727999/183456947-c09c9074-ac7a-43d0-9fa8-38cc2c956d48.mov

**After moving to the branch feature/FOUR-6104B, email servers 1, 2 and 3 were removed. Also there are errors showing in terminal when trying to migrate core and install package auth**

https://user-images.githubusercontent.com/90727999/183457438-a88e5583-2203-42cc-b4ed-5c4a828398f3.mov

**Review by agustinbusso — COMMENTED** [review]
- Authorize account **[CORRECT]**

https://user-images.githubusercontent.com/90727999/183508135-c92c83e8-7de0-4e23-a079-a44685bf8d6e.mov

**Review by agustinbusso — COMMENTED** [review]
- Send test email **[CORRECT]**

https://user-images.githubusercontent.com/90727999/183509419-58dd1ef5-3c7a-4395-86c7-39bc96caebd4.mov

**Comment by agustinbusso** [comment]
- Send email with connector email **[CORRECT]**

https://user-images.githubusercontent.com/90727999/183512597-deb1afe1-a117-44b5-80ce-9082d76efb86.mov

**Review by agustinbusso — APPROVED** [review]

**Review by marcoAntonioNina — APPROVED** [review]

**Pull request merged**
