### PR TITLE
Add warnings, recommendations and helper text.

### PR DESCRIPTION
**Pull request by caleeli**
Resolves: http://tickets.pm4overflow.com/tickets/167

Add warnings, recommendations and helper text.

image

image

image

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-167-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-167-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-167-processmaker.ci.processmaker.net

**Review by ryancooley — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-167-processmaker.ci.processmaker.net

**Pull request merged**
