### PR TITLE
Removed space to fix translation issue - 4.1

### PR DESCRIPTION
**Pull request by PMQABen**
Fixes part of https://processmaker.atlassian.net/browse/FOUR-4138 for 4.1

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://four-4138_fix4-1-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://four-4138_fix4-1-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://four-4138_fix4-1-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://four-4138_fix4-1-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://four-4138_fix4-1-processmaker.ci.processmaker.net

**Review by sanjacornelius — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://four-4138_fix4-1-processmaker.ci.processmaker.net

**Pull request merged**
