### PR TITLE
Trigger CI pipeline - do not merge

### PR DESCRIPTION
**Pull request by nolanpro**
Testing CI environment variables

ci:MY_CUSTOM_VAR="A custom value from the PR"
ci:TELESCOPE_ENABLED=true

ci:deploy

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-25c341a522.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-25c341a522.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-25c341a522.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-25c341a522.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-25c341a522.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-25c341a522.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed 2023-06-23T18:49:25+00:00

**Comment by pmkerberos** [comment]
QA server was successfully deployed 2023-06-23T19:49:59+00:00

**Comment by pmkerberos** [comment]
QA server was successfully deployed 2023-06-23T20:24:43+00:00

**Comment by pmkerberos** [comment]
QA server was successfully deployed 2023-06-23T20:55:02+00:00

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-25c341a522.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-25c341a522.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-25c341a522.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-25c341a522.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-25c341a522.eng.processmaker.net

**Pull request closed without merging**
