### PR TITLE
FOUR-9993 - Add "Download" button in AI Designer to save the model as a PDF

### PR DESCRIPTION
**Pull request by eiresendez**
## Issue & Reproduction Steps
As a Process Analyst, I want a downloadable option for the process model within the **AI designer**, so that I can easily share, review, and archive process models offline or with stakeholders who may not have direct access to the application.

1. Go to the AI Designer at `/package-ai/processes/create`.
2. Generate a new process.
3. The user clicks the "Download" button on the AI designer screen. 
4. The application generates an image file of the process model.
5. The application completes the download and open the generated file in the browser.

## Solution
- Added a new npm dependencies: `canvg`.
  _- The `canvg` dependency could later be removed if a manual alternative is found._
- Created new shared component "DownloadSvgButton.vue".

Screenshot_2023-08-21_at_14-44-51_Generative_AI_-_ProcessMaker

## How to Test
- Please follow the reproduction steps of above.

## Related Tickets & Packages
- [FOUR-9993](https://processmaker.atlassian.net/browse/FOUR-9993)
- [PLAT-45](https://processmaker.atlassian.net/browse/PLAT-45)
- [Download Process Model Confluence](https://processmaker.atlassian.net/wiki/spaces/S/pages/3164569637/Download+Process+Model)
- [Package AI PR](https://github.com/ProcessMaker/package-ai/pull/16)
- [Modeler PR](https://github.com/ProcessMaker/modeler/pull/1653)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

[FOUR-9993]: https://processmaker.atlassian.net/browse/FOUR-9993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci:deploy
ci:modeler:task/FOUR-9993
ci:package-ai:task/FOUR-9993

### CODE REVIEW

**Review by agustinbusso — CHANGES_REQUESTED** [review]
@eiresendez the changes looks great! Only two small observations (maybe is overcomplicated because libraries limitations)

- The arrows of the sequence flows are not rendered
- The text of the flows are not correctly placed

Screenshot 2023-08-22 at 11 54 34

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-eb38d8ad78.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-eb38d8ad78.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-eb38d8ad78.eng.processmaker.net

**Review by agustinbusso — APPROVED** [review]
The fix is correct, the process is exported as png. It's necessary to update the PRD because we are not exporting a PDF:

https://github.com/ProcessMaker/modeler/assets/90727999/843afebe-d1bd-40c5-9091-162a0cdddbaa

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-eb38d8ad78.eng.processmaker.net

**Pull request merged**
