### PR TITLE
Fix Status field name

### PR DESCRIPTION
**Pull request by caleeli**
Fix field name from "size" to "status"
fix-status-field-name

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-378-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-378-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-378-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-378-processmaker.ci.processmaker.net

**Review by danloa — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-378-processmaker.ci.processmaker.net

**Pull request merged**
