### PR TITLE
Resolve 'Not authorized to update user' error when creating new script

### PR DESCRIPTION
**Pull request by sanjacornelius**
This PR resolves an issue where users with only Project Permissions were encountering a `Not authorized to update this user` error when creating a new script. The error was caused by an API request fetching the admin user and setting them as the default 'Run as User' in the Create Script Modal.

## Solution
The solution involves refactoring how the admin user is set as the default 'Run as User.' Instead of an additional API request, a query `User::where('name', 'admin')->first();` is used to retrieve the full user object. This user object is stored in a variable `runAsUserDefault` and passed into the Create Script Modal component.

## Changes
Refactored the default 'Run as User' selection to avoid additional API requests, ensuring compatibility with users having only Project Permissions.

## How to Test

**Testing Projects**

1. Ensure you have a user with only Project permissions.
2. Login with that user.
3. Navigate to Designer > Projects.
4. Click '+ Asset.'
5. Create a new script.
6. Verify no errors occur during this process.
7. Select the 'Advanced options' accordion.
8. Verify the admin user is selected by default.
9. Create the script.
10. Verify the script is created with no errors.

**Testing Scripts**

1. Login as a user with all permissions or script permissions.
2. Navigate to Designer > Script.
3. Create a new script.
4. Select the 'Advanced options' accordion.
5. Verify the admin user is selected by default.
6. Create the script.
7. Verify the script is created with no errors.

## Related Tickets & Packages
- [FOUR-12744](https://processmaker.atlassian.net/browse/FOUR-12744)
- [Projects PR](https://github.com/ProcessMaker/package-projects/pull/89)

ci:deploy
ci:next
ci:package-projects:observation/FOUR-12744

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

[FOUR-12744]: https://processmaker.atlassian.net/browse/FOUR-12744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0a15c6865b.eng.processmaker.net

**Comment by pmPaulis** [comment]
@sanjacornelius 
I tried to create a script task but I didn't, I tested in the enviroment related to the PR.
image

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0a15c6865b.eng.processmaker.net

**Review by fagubla — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0a15c6865b.eng.processmaker.net

**Review by pmPaulis — APPROVED** [review]

**Pull request merged**
