### PR TITLE
Do not redirect closed tasks either. Redirects are handled in advanced forms

### PR DESCRIPTION
**Pull request by nolanpro**
Fixes part of https://processmaker.atlassian.net/browse/FOUR-2915

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2915-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2915-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2915-processmaker.ci.processmaker.net

**Review by sanjacornelius — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2915-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2915-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-1-processmaker.ci.processmaker.net

**Pull request merged**
