### PR TITLE
feature/FOUR-17896: [FALL] Documentation Access Management and Navigation

### PR DESCRIPTION
**Pull request by pmPaulis**
## Issue & Reproduction Steps
Admins currently lack the ability to specifically grant or restrict access to process documentation, leading to potential issues with unauthorized access or inadequate visibility. Additionally, users with view permissions have difficulty navigating from parent processes to their associated sub-processes, which hampers their ability to efficiently access relevant documentation.

**PRD**
[Documentation Access Management and Navigation](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3581771777/Documentation+Access+Management+and+Navigation) 

**FIGMA**
https://www.figma.com/design/Jfl3HAOx28TVHMl7cHJNIP/Fall-2024?node-id=701-12973

## Stories

1. Admin Capability to Grant Process Documentation Access
2. Documentation Navigation Capability
3. Adjust the behaivor of Add Projects option y Launchpad
4. View Documentation Option

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-17896

## PR Related
https://github.com/ProcessMaker/package-process-documenter/pull/34
https://github.com/ProcessMaker/package-ai/pull/291

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy
ci:package-process-documenter:feature/FOUR-17896
ci:package-ai:feature/FOUR-17896

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ac71a95ccd.engk8s.processmaker.net

**Review by fagubla — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ac71a95ccd.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ac71a95ccd.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ac71a95ccd.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ac71a95ccd.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ac71a95ccd.engk8s.processmaker.net

**Pull request merged**
