### PR TITLE
Redesign notification bell popover

### PR DESCRIPTION
**Pull request by nolanpro**
## Issue & Reproduction Steps
See
- https://processmaker.atlassian.net/browse/FOUR-9710
- https://processmaker.atlassian.net/browse/FOUR-10163
- PRD: https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3148578817/Notifications+Overhaul

Requires https://github.com/ProcessMaker/package-comments/pull/89

ci:next
ci:deploy
ci:package-comments:feature/FOUR-9709
.

## Solution
- Redesign the bell icon popover window
- Standardize notification messages
- Remove the items once viewed

## How to Test
Create a number of notifications. For example
- Comments
- Process started
- Task assigned

You can put viewed messages back in the popover by going to the `/notifications` page and clicking the mail icon to un-read

Ensure it matches the Figma in the [PRD](https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3148578817/Notifications+Overhaul)

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-9710
- https://processmaker.atlassian.net/browse/FOUR-10163
- https://github.com/ProcessMaker/package-comments/pull/89

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-5ef14792c0.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-5ef14792c0.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-5ef14792c0.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-5ef14792c0.eng.processmaker.net

**Review by gproly — APPROVED** [review]

**Pull request merged**
