### PR TITLE
Implement Search Functionality for My Screen Templates Tab

### PR DESCRIPTION
**Pull request by sanjacornelius**
This PR introduces the search functionality for the My Screen Templates tab. Users can now search for specific screen templates based on their names, descriptions, and category.

## Solution

- Implemented the `ExtendedPMQL` trait for the Screen Templates model to enable advanced search capabilities.
- Developed the `PmqlInput` component to provide a user-friendly interface for entering search queries.
- Added the `index` method for Screen Templates to handle the search functionality and display the results accordingly.

## How to Test

1. Navigate to the My Screen Templates tab.
2. Utilize the search input field to enter a query (e.g., screen template name or description).
3. Verify that the search results update dynamically as you type.
4. Try different search queries to ensure accurate and relevant results are displayed.

## Related Tickets & Packages
- [FOUR-13483](https://processmaker.atlassian.net/browse/FOUR-13483)

ci:next
ci:deploy

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

[FOUR-13483]: https://processmaker.atlassian.net/browse/FOUR-13483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-aebf20cc16.engk8s.processmaker.net

**Review by eiresendez — CHANGES_REQUESTED** [review]
hi @sanjacornelius 

1. I have left some comments regarding SQL queries. 
2. For some reason, the name column is not displaying under this condition `<template v-if="header.field === 'name'">` Could be an issue with my local env? 
3. Also, something unusual happens when I try to search using the term `Admin`
4. it seems that it's not filtering templates when they're of the type `is_system`


https://github.com/ProcessMaker/processmaker/assets/90741874/df146336-0d8f-4ca2-808d-0cb0d8723ea9

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-aebf20cc16.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-aebf20cc16.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-aebf20cc16.engk8s.processmaker.net

**Review by eiresendez — APPROVED** [review]
Everything is working great!

**Pull request merged**
