### PR TITLE
FOUR-9372 - Show default screen for display and form tasks

### PR DESCRIPTION
**Pull request by eiresendez**
## Issue & Reproduction Steps
The default screens will be displayed when the user doesn't select a screen in the Modeler for a Form or Manual task. It will also be displayed when there's no reference to a screen or when a screen does not exist.

## Solution
- The screens were generated using the ScreenBuilder according to the Figma mockup.
- The screens were exported and the JSON files were stored in `database/processes/screens`.
- The default system screens were installed by running the seeder `php artisan db:seed --class="ScreenSystemSeeder"`.
- The default screen is obtained if necessary and whether it's a manual or form task.
- It also works for nested screens.
- It also works for web entry tasks and start event.

## How to Test
- Please run the seeder: `php artisan db:seed --class="ScreenSystemSeeder"` and execute manual tests.
- Execute manual tests in the provided QA server.

## Related Tickets & Packages
- [FOUR-9372](https://processmaker.atlassian.net/browse/FOUR-9372)
- [Package Web Entry PR](https://github.com/ProcessMaker/package-webentry/pull/210)
 
## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:package-webentry:feature/FOUR-9372

[FOUR-9372]: https://processmaker.atlassian.net/browse/FOUR-9372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by eiresendez** [comment]
Examples:

example-default-display-screen
example-default-form-screen

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-2f28fcef16.eng.processmaker.net

**Comment by eiresendez** [comment]
Example for Nested Screens:

example-default-nested-screen

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-2f28fcef16.eng.processmaker.net

**Comment by eiresendez** [comment]
Example for Web Entry:

Screen Shot 2023-07-19 at 11 12 24 a m

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-2f28fcef16.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-2f28fcef16.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-2f28fcef16.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-2f28fcef16.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-2f28fcef16.eng.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Pull request merged**
