### PR TITLE
Allow REASSIGN tasks in overdue

### PR DESCRIPTION
**Pull request by caleeli**
Fixes: https://processmaker.atlassian.net/browse/FOUR-3741

This PR includes:

- Add condition to show REASSIGN for overdue tasks

image

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3741b-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3741b-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3741b-processmaker.ci.processmaker.net

**Review by nolanpro — APPROVED** [review]
Works as expected in 4.2

**Pull request merged**
