### PR TITLE
[SUMMER] feature/FOUR-15725 Improve Tables View for tasks and cases

### PR DESCRIPTION
**Pull request by gustavobascope**
## Issue & Reproduction Steps
Improve Tables View for tasks and cases

## Solution

- Case Title column will have the Draft tag in order to show the tasks that has Draft in progress.
- Status column should show a diferent design.
- Tasks: The style and appearance is the same that the one stablished in Core Table Component, but with additional functionalities
- All texts on the table, in their idle state, have to be black (the tone of black used in this design) and only change in color when interacting (hovering)  with them.
- The cursor has to change to a hand in the case that the text is interactive.
- Tasks: new tasks are highllighted in yellow.
- Case Title Cells: The case title should be a link, and when pressed it has to lead to the TASK, not to the case (since we are in the inbox screen) this behavior should only be seen in this screen.

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-15725

ci:next
ci:deploy
ci:package-savedsearch:feature/FOUR-15725

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-d193774fa9.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-d193774fa9.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-d193774fa9.engk8s.processmaker.net

**Review by nolanpro — CHANGES_REQUESTED** [review]
Hi @gustavobascope 
- I noticed the custom columns in /tasks have this weird gray background 
image
- I noticed the yellow background doesn't go away when you click the back button. It does go away when you reload the page, so this might be a caching issue. Can you think of any way we can remove the yellow background when the user clicks the back button?

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-d193774fa9.engk8s.processmaker.net

**Comment by gustavobascope** [comment]
> nolanpro
I pushed a fix for the back button on the web browser and I also pushed a fix for the filter and sort styles

**Review by nolanpro — APPROVED** [review]

**Pull request merged**
