### PR TITLE
Fix: Reduce Database Bloat in Guided Templates

### PR DESCRIPTION
**Pull request by sanjacornelius**
## Issue & Reproduction Steps
This PR resolves an issue with Guided Templates causing database bloat whenever a guided template sync command is run multiple times. The problem stemmed from the creation of new version records for all guided template assets each time a guided template sync command was executed. This resulted in unintended database bloat and increased spin-up time for servers required by the PLG team.

## Solution
To address this, the solution involves a hashing mechanism that only imports the helper process or process template when the hash has changed.  Unnecessary database bloat is prevented, leading to improved database performance and reduced resource consumption.

## How to Test

1. Ensure access to an environment database.
2. Run a guided template sync command multiple times.
3. Check the asset versions table (e.g., screen_versions, script_versions) in the database.
4. Verify that no new version records are created for guided template assets after running the guided template.
5. Repeat the test with multiple guided templates to confirm consistent behavior.
6. Compare database size and performance metrics before and after implementing the fix to observe the reduction in database bloat and improved performance.

## Related Tickets & Packages
- [FOUR-15105](https://processmaker.atlassian.net/browse/FOUR-15105)

ci:next
ci:GUIDED_TEMPLATE_BRANCH=observation/FOUR-15105

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

[FOUR-15105]: https://processmaker.atlassian.net/browse/FOUR-15105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-6ac0a2efc2.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-6ac0a2efc2.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-6ac0a2efc2.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-6ac0a2efc2.engk8s.processmaker.net

**Review by estebangallego — APPROVED** [review]

**Pull request merged**
