### PR TITLE
[FOUR-11555] Add support for Cypress coverage reporting

### PR DESCRIPTION
**Pull request by ryancooley**
ci:next
ci:deploy

ci:connector-docusign:coverage
ci:connector-idp:coverage
ci:connector-pdf-print:coverage
ci:connector-slack:coverage
ci:package-actions-by-email:coverage
ci:package-advanced-user-manager:coverage
ci:package-ai:coverage
ci:package-analytics-reporting:coverage
ci:package-auth:coverage
ci:package-cdata:coverage
ci:package-collections:coverage
ci:package-comments:coverage
ci:package-conversational-forms:coverage
ci:package-data-sources:coverage
ci:package-decision-engine:coverage
ci:package-dynamic-ui:coverage
ci:package-files:coverage
ci:package-googleplaces:coverage
ci:package-photo-video:coverage
ci:package-pm-blocks:coverage
ci:package-process-documenter:coverage
ci:package-process-optimization:coverage
ci:package-projects:coverage
ci:package-sentry:coverage
ci:package-signature:coverage
ci:package-testing:coverage
ci:package-translations:coverage
ci:package-versions:coverage
ci:package-vocabularies:coverage
ci:package-webentry:coverage

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-f1cc64d763.eng.processmaker.net

**Review by josechirivella — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-f1cc64d763.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-f1cc64d763.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-f1cc64d763.eng.processmaker.net

**Pull request merged**
