### PR TITLE
[4.1] Ticket #727: Saved Search Issues

### PR DESCRIPTION
**Pull request by ryancooley**
## Fixes
- [FOUR-3996](https://processmaker.atlassian.net/browse/FOUR-3996) Screen building inspector chart select showing only 10 charts - should show all
- [FOUR-4036](https://processmaker.atlassian.net/browse/FOUR-4036) No results in a search changing tabs
- [FOUR-3633](https://processmaker.atlassian.net/browse/FOUR-3633) Swagger example results in 422 error
- [FOUR-4024](https://processmaker.atlassian.net/browse/FOUR-4024) Searching with PMQL input should be expected to be in the logged in user's timezone
- [FOUR-3360](https://processmaker.atlassian.net/browse/FOUR-3360) Super-Admin permission must allow user to see ALL saved searches
- [FOUR-3932](https://processmaker.atlassian.net/browse/FOUR-3932) After clearing Task saved search you cannot search by Request name
- [FOUR-3933](https://processmaker.atlassian.net/browse/FOUR-3933) Text Search in filters not working
- [FOUR-3951](https://processmaker.atlassian.net/browse/FOUR-3951) Task Saved Search includes unrelated results
- Cannot use greater than in PMQL with Saved Search API

## Requires
- https://github.com/ProcessMaker/package-savedsearch/pull/269

## 4.2 Equivalent
- https://github.com/ProcessMaker/processmaker/pull/4025

## Ticket
- http://tickets.pm4overflow.com/tickets/727

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ticket-727-4-1-all-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ticket-727-4-1-all-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ticket-727-4-1-all-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ticket-727-4-1-all-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ticket-727-4-1-all-processmaker.ci.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ticket-727-4-1-all-processmaker.ci.processmaker.net

**Pull request merged**
