### PR TITLE
[SPRING] observation/FOUR-14616 Disable functionality in tasks lists

### PR DESCRIPTION
**Pull request by gustavobascope**
## Issue & Reproduction Steps
Disable functionality in tasks lists

## Solution
Disable row click and ellipsis menu on Define the filtering criteria in inbox rules new/edit page

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-14616

ci:deploy
ci:next
.

### CODE REVIEW

**Review by nolanpro — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-5e85d880c5.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-5e85d880c5.engk8s.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-5e85d880c5.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-5e85d880c5.engk8s.processmaker.net

**Pull request merged**
