### PR TITLE
Remove web entry start events from the new request modal

### PR DESCRIPTION
**Pull request by nolanpro**
Fixes https://processmaker.atlassian.net/browse/FOUR-2820

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2820-processmaker.ci.processmaker.net

**Comment by sanjacornelius** [comment]
@nolanpro The web entry process does not show in the '+Request' modal but I do get this error in the console.

Screen Shot 2021-02-16 at 10 16 42 AM

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2820-processmaker.ci.processmaker.net

**Review by sanjacornelius — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Pull request merged**
