### PR TITLE
FOUR-5822: Bad data in notifications table

### PR DESCRIPTION
**Pull request by danloa**
## Issue & Reproduction Steps
- Edit or Insert any item of the "notifications" table, taking care of setting a simple string (for instance "mystring") for the "data" column . 
- In PM4 go to tasks and open any task.
- An error "Invalid JSON text in argument 1 to function json_extract"  will be displayed.

## Solution
The queries that are used to extract json information from the "data" column of the "notifications" table have been  modified so that the validity of the json string is checked first.

## How to Test
- Edit or Insert any item of the "notifications" table, taking care of setting a simple string (for instance "mystring") for the "data" column . 
- In PM4 go to tasks and open any task.

All tasks listings and editing a task should work without problems

## Related Tickets & Packages
[https://processmaker.atlassian.net/browse/FOUR-5822](https://processmaker.atlassian.net/browse/FOUR-5822)

## Code Review Checklist
- [x] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [x] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [x] This solution fixes the bug reported in the original ticket.
- [x] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [x] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [x] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [x] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [x] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5822-processmaker.ci.processmaker.net

**Review by eiresendez — CHANGES_REQUESTED** [review]
Hi @danloa ... the new constraint fixes the problem... but if I go to another page i.e. `/requests` I get the same error. I wonder if adding this as a global scope could be a good idea:

```
static::addGlobalScope('valid', function (Builder $builder) {
    $builder->whereRaw('json_valid(data)');
});
```

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5822-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5822-processmaker.ci.processmaker.net

**Review by eiresendez — APPROVED** [review]

**Review by ryancooley — APPROVED** [review]

**Pull request merged**
