### PR TITLE
FOUR-2539

### PR DESCRIPTION
**Pull request by GooseCoder**
Adding new date format entries.

### CODE REVIEW

**Review by nolanpro — CHANGES_REQUESTED** [review]
@GooseCoder i'm getting this on the requests/all page on those last 2. Looks javascript so its probably something to do with the momentFormat 
image

**Comment by nolanpro** [comment]
Needed to rebuild assets

**Review by nolanpro — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2451-processmaker.ci.processmaker.net

**Pull request merged**
