### PR TITLE
observation/FOUR-13973 In processes some columns are not resizing

### PR DESCRIPTION
**Pull request by gustavobascope**
## Issue & Reproduction Steps
In processes some columns are not resizing

## Solution
fixed the column attributes and added sorting

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-13973

ci:deploy
ci:next

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a947944215.engk8s.processmaker.net

**Review by nolanpro — CHANGES_REQUESTED** [review]
@gustavobascope A few things I noticed

- Can we fix this problem where dragging is causing the text to truncate even when the column is not moving?
  

https://github.com/ProcessMaker/processmaker/assets/2546850/1453c6d6-d2f4-4507-8bc1-39334bf2b1bd



- It seems to cut off more space then necessary. The red boxes are empty space that could be used:
  image

- Can we fix the background color? It looks like it shifted a few pixels to the right. It should fit inside the grey lines:
  image

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a947944215.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a947944215.engk8s.processmaker.net

**Comment by gustavobascope** [comment]
> @gustavobascope A few things I noticed
> 
> * Can we fix this problem where dragging is causing the text to truncate even when the column is not moving?
> 
>  column1.mov 
> * It seems to cut off more space then necessary. The red boxes are empty space that could be used:
>   image
> * Can we fix the background color? It looks like it shifted a few pixels to the right. It should fit inside the grey lines:
>   image

@nolanpro  I solved the observations

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a947944215.engk8s.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Comment by nolanpro** [comment]
@gustavobascope looks good, thanks!

**Pull request merged**
