### PR TITLE
FOUR-11405 | When Closing a Created Asset (From ‘+Asset’), After Publishing and Closing It, Redirect Back to the Project

### PR DESCRIPTION
**Pull request by mcraeteisha**
# Issue
Ticket: [FOUR-11405](https://processmaker.atlassian.net/browse/FOUR-11405)

In a Project's Asset Listing, when a new asset is created, after that asset has been saved, the user should be redirected back to the Project they created the asset from.

# Solution
- Implement redirects for Processes, Screens, Scripts, Data Sources, and Decision Tables from the respective creation modals.

# How to Test
1. Go to branch `observation/FOUR-11405` in `processmaker`.
2. Go to branch `observation/FOUR-11405` in `package-projects`.
3. Go to branch `observation/FOUR-11405` in `package-data-sources`.
4. Go to branch `observation/FOUR-11405` in `package-decision-engine`.
5. Go to branch `observation/FOUR-11405` in `package-ai`.
6. Go to Designer → Projects. Open a Project.
7. Create a new Process from within the Asset Listing.
	- You should be redirected to the Process Modeler.
8. Save your Process.
	- You should be redirected back to your Project.
9. Repeat for all asset types.
10. Ensure that when creating an asset (a Process, Screen, or Script) from a Process using AI Generation, you are redirected back to the Process Modeler.

ci:next
ci:package-projects:observation/FOUR-11405
ci:package-data-sources:observation/FOUR-11405
ci:package-decision-engine:observation/FOUR-11405
ci:package-ai:observation/FOUR-11405
ci:deploy

# Code Review Checklist

- [ ]  I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ]  This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ]  This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ]  This solution fixes the bug reported in the original ticket.
- [ ]  This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ]  This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ]  This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ]  This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ]  This ticket conforms to the PRD associated with this part of ProcessMaker.

[FOUR-11405]: https://processmaker.atlassian.net/browse/FOUR-11405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-6ab3005d93.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-6ab3005d93.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-6ab3005d93.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-6ab3005d93.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-6ab3005d93.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-6ab3005d93.eng.processmaker.net

**Review by sanjacornelius — APPROVED** [review]

**Comment by sanjacornelius** [comment]
Closing as no longer needed due to complication with the AI Package redirect. This ticket will be resolved by a US for Winter 2024

**Pull request closed without merging**
