### PR TITLE
Make sure Tool Tip to view collections displays View Collection

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
Fixes [FOUR-3376](https://processmaker.atlassian.net/browse/FOUR-3376)

- change regex for collection name

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3376-a-processmaker.ci.processmaker.net

**Review by ryancooley — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3376-a-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3376-a-processmaker.ci.processmaker.net

**Pull request merged**
