### PR TITLE
FOUR-13910 block duplicate session in device restriction only works when the initial browser has the session open

### PR DESCRIPTION
**Pull request by devmiguelangel**
## Issue & Reproduction Steps
The application is only logged in again when we log in with browser 1, which was the one that had the session.

## Solution
Check all active sessions in block session by device

## How to Test
1. login with a user with device 1 
2. have the "Block duplicate session" option in device restriction enabled
3. I will open another device 2
4. try to log in with the same username from the other browser (this is correct)
5. We go to device 1 and log out
6. We return to device 2 and try to log in again

## Related Tickets & Packages
[FOUR-13910](https://processmaker.atlassian.net/browse/FOUR-13910)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy

[FOUR-13910]: https://processmaker.atlassian.net/browse/FOUR-13910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-f3d9ccf205.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-f3d9ccf205.engk8s.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-f3d9ccf205.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-f3d9ccf205.engk8s.processmaker.net

**Review by caleeli — APPROVED** [review]

**Pull request merged**
