### PR TITLE
Fix Select Lists populating Collections

### PR DESCRIPTION
**Pull request by sanjacornelius**
**Jira Ticket**
https://processmaker.atlassian.net/browse/FOUR-2985

<h2>Changes</h2>

- Fix the `Undefined body_type` error when using collections to populate a select list.

**Video**

https://www.loom.com/share/adf4246707c64da9a042e570be36c8d0

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2985-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2985-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2985-processmaker.ci.processmaker.net

**Review by marcoAntonioNina — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2985-processmaker.ci.processmaker.net

**Pull request merged**
