### PR TITLE
feature/FOUR-17895: [FALL] Task Submitted Successfully - toast replacement notification

### PR DESCRIPTION
**Pull request by pmPaulis**
## Task Submitted Successfully - toast replacement notification
Users are often unsure if their tasks have been successfully submitted, leading to confusion, repeated submissions, or unnecessary navigation to confirm task status. This uncertainty disrupts their workflow and diminishes their overall user experience.
## PRD
https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3551395942/Task+Submitted+Successfully+-+Toast+replacement+notification 
## FIGMA
 https://www.figma.com/design/Jfl3HAOx28TVHMl7cHJNIP/Fall-2024?node-id=222-1885&t=kaD6pOIRfTCtKckR-0 

## Solution
- As a user while filling out a form, I would like to know that autosave is working correctly without the need for recurring pop-up messages with every change.

## How to Test
1. Login into ProcessMaker
2. Open a Task
3. Fill a Form
4. While user is filling out the form the information the information will have an automatic autosave with a new UI

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-17895

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-912ed4a32a.engk8s.processmaker.net

**Review by fagubla — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-912ed4a32a.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-912ed4a32a.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-912ed4a32a.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-912ed4a32a.engk8s.processmaker.net

**Pull request merged**
