### PR TITLE
Epic/FOUR-11531: [PRD] Process LaunchPad IT2

### PR DESCRIPTION
**Pull request by pmPaulis**
## Issue & Reproduction Steps
Process LaunchPad
https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3232301057/Process+LaunchPad

https://www.figma.com/file/bI3YLt9n2771ReExAQIggs/Winter24?type=design&mode=design&t=3rPEwvG6sK5NdKXv-0

## Solution
**11. Designer menu**
As a Designer, I want to see a menu with designer options (ellipsis from process list) including editing the launchpad.
	
**12. Launchpad setup**
As process author, after first publishing the process, I want the option to configure the launchpad (icon, thumbnail, grouped by chart).
This option Launchpad should go in the initial configuratioon of the process.

## How to Test
1. Enter a process to access its Launchpad.
3. See a menu with Designer options (ellipsis from process list)

## Related Tickets & Packages
- [Link to any related FOUR tickets, PRDs, or packages](https://processmaker.atlassian.net/browse/FOUR-11531)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next
ci:package-versions:feature/FOUR-11531
ci:package-analytics-reporting:bugfix/FOUR-12650
.

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Review by fagubla — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-8c603e9eba.eng.processmaker.net

**Pull request merged**
