### PR TITLE
epic/FOUR-11496: [PRD] New Script Modal Redesign IT1

### PR DESCRIPTION
**Pull request by pmPaulis**
## Issue & Reproduction Steps
This feature addresses the common pain point of time-consuming CSS fine-tuning and manual adjustments for design elements like borders and spacing on every page.

## Solution
- The new feature will change the interfaz to create a new Script

## How to Test
- Create a new script

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-11496
## Code Review Checklist
- [x] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next
ci:package-projects:feature/FOUR-11496

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-36e6c00df8.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-36e6c00df8.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-36e6c00df8.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-36e6c00df8.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-36e6c00df8.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-36e6c00df8.eng.processmaker.net

**Review by fagubla — APPROVED** [review]

**Review by luNunezProcessmaker — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-36e6c00df8.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-36e6c00df8.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-36e6c00df8.eng.processmaker.net

**Comment by pmPaulis** [comment]
The following is a video to explain how will work the PRD

https://github.com/ProcessMaker/processmaker/assets/42388723/4c213a69-58a6-4be5-b2f8-c66b86bc499f

**Pull request merged**
