### PR TITLE
Add Self Service Support for Manual Tasks

### PR DESCRIPTION
**Pull request by sanjacornelius**
**Jira Ticket**

https://processmaker.atlassian.net/browse/FOUR-2911

<h2>Changes</h2>

- Adds self-service support for Manual Tasks

**Video**

https://www.loom.com/share/d9fca08568db46f18891054f798335bf

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2911-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2911-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2911-processmaker.ci.processmaker.net

**Review by caleeli — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2911-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2911-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2911-processmaker.ci.processmaker.net

**Pull request merged**
