### PR TITLE
Laravel 8.x Shift

### PR DESCRIPTION
**Pull request by nolanpro**
Upgrade to Laravel 8

Requires php 8. I recommend using Laravel Valet if you are on a mac with the bare-metal setup.

NOTE: PMQL is referencing the branch in composer.json. Before releasing, release PMQL first and update composer.json to the actual version.

https://github.com/ProcessMaker/pmql/pull/31

https://github.com/ProcessMaker/package-auth/pull/68
https://github.com/ProcessMaker/connector-docusign/pull/29
https://github.com/ProcessMaker/connector-slack/pull/19
https://github.com/ProcessMaker/package-actions-by-email/pull/89
https://github.com/ProcessMaker/package-dynamic-ui/pull/64
https://github.com/ProcessMaker/package-signature/pull/29
https://github.com/ProcessMaker/package-translations/pull/50
https://github.com/ProcessMaker/package-vocabularies/pull/68
https://github.com/ProcessMaker/package-collections/pull/326
https://github.com/ProcessMaker/connector-send-email/pull/223
https://github.com/ProcessMaker/package-comments/pull/82
https://github.com/ProcessMaker/package-data-sources/pull/241
https://github.com/ProcessMaker/package-files/pull/86
https://github.com/ProcessMaker/package-savedsearch/pull/327
https://github.com/ProcessMaker/package-versions/pull/54
https://github.com/ProcessMaker/package-webentry/pull/170
https://github.com/ProcessMaker/package-skeleton/pull/6
https://github.com/ProcessMaker/package-ellucian-ethos/pull/80
https://github.com/ProcessMaker/customer-adoa/pull/94
https://github.com/ProcessMaker/package-migration-tools/pull/29
https://github.com/ProcessMaker/docker-executor-php/pull/17
https://github.com/ProcessMaker/package-advanced-user-manager/pull/27
https://github.com/ProcessMaker/package-googleplaces/pull/34
https://github.com/ProcessMaker/package-process-documenter/pull/23
https://github.com/ProcessMaker/package-process-optimization/pull/15
https://github.com/ProcessMaker/package-sentry/pull/9
https://github.com/ProcessMaker/package-stm/pull/7
https://github.com/ProcessMaker/package-data-sources/pull/241

ci:base:2.1.0

ci:connector-slack:feature/FOUR-6565
ci:connector-send-email:feature/FOUR-6565
ci:connector-docusign:feature/FOUR-6565
ci:package-auth:feature/FOUR-6565
ci:package-translations:feature/FOUR-6565
ci:package-vocabularies:feature/FOUR-6565
ci:package-versions:feature/FOUR-6565
ci:package-comments:feature/FOUR-6565
ci:package-signature:feature/FOUR-6565
ci:package-actions-by-email:feature/FOUR-6565
ci:package-data-sources:feature/FOUR-6565
ci:package-collections:feature/FOUR-6565
ci:package-savedsearch:feature/FOUR-6565
ci:package-dynamic-ui:feature/FOUR-6565
ci:package-webentry:feature/FOUR-6565
ci:package-files:feature/FOUR-6565
ci:docker-executor-php:feature/FOUR-6565
ci:package-advanced-user-manager:feature/FOUR-6565
ci:package-googleplaces:feature/FOUR-6565
ci:package-process-documenter:feature/FOUR-6565
ci:package-process-optimization:feature/FOUR-6565
ci:package-sentry:feature/FOUR-6565
ci:package-stm:feature/FOUR-6565

### CODE REVIEW

**Comment by nolanpro** [comment]
:warning: Shift detected a custom namespace. Laravel now recommends keeping the default `App` namespace. While it was available to customize in previous versions using `app:name`, this command was removed in Laravel 6.0.

Shift recommends changing this to align with Laravel and improve its automation. After doing so, you are welcome to request a rerun of this Shift.

**Comment by nolanpro** [comment]
:x: Shift could not upgrade the following files since they differed from the default Laravel version. You will need to compare these files against the [default Laravel 8 versions](https://github.com/laravel-shift/laravel-8.x/) and merge any changes:

- [ ] public/index.php
- [ ] resources/lang/en/validation.php

**Comment by nolanpro** [comment]
:warning: Laravel 8 renamed the `CheckForMaintenanceMode` middleware to `PreventRequestsDuringMaintenance`. Shift [automated this change](https://github.com/ProcessMaker/processmaker/pull/4483/commits/e793f929b613e0b2b9ea02ddcf4d09d636fd1354?w=1) for your middleware and `Http\Kernel`, but detected potential references to `CheckForMaintenanceMode` in the following files. You should review these files and update any references accordingly.

- [ ] ProcessMaker/Http/Kernel.php

**Comment by nolanpro** [comment]
:x: Shift was unable to find some of your controllers and left them as string references in your routes.

You will need to search for the following controller names in your routes and replace them with the appropriate static `::class` reference manually.

- [ ] Process\ModelerController

**Comment by nolanpro** [comment]
:information_source: Laravel 8 introduced class based factories. Shift [automated this change](https://github.com/ProcessMaker/processmaker/pull/4483/commits/a897cce82ddeab9b491b889618ebe3d2fe3b33b6?w=1). However, if you were using a community package for factories or other custom code, you should review your factories for additional changes.

If you encounter an issue, you may revert this commit and temporarily install the [laravel/legacy-factories](https://github.com/laravel/legacy-factories) package. You may then automate the conversion to class based factories using the [Shift Workbench](https://laravelshift.com/workbench).

**Comment by nolanpro** [comment]
:information_source: Laravel 8 added a `uuid` column to the `failed_jobs` table to support the new [job batching](https://laravel.com/docs/8.x/queues#job-batching) features. Shift detected you have a migration for this table and [created a migration](https://github.com/ProcessMaker/processmaker/pull/4483/commits/23ab08dc69d25a12dbca98d4dcf84a5ed4dae01a?w=1) for this new column. Be sure to run `php artisan migrate` to complete your upgrade.

**Comment by nolanpro** [comment]
:information_source: Laravel 8 added new ENV variables for `AWS_USE_PATH_STYLE_ENDPOINT`, `LOG_LEVEL`, and `LOG_DEPRECATIONS_CHANNEL`. While these are defaulted within their respective configuration file, you may take this opportunity to set them accordingly for your environments.

**Comment by nolanpro** [comment]
:warning: Shift upgraded your configuration files by defaulting them and merging your _true customizations_. These include values which are not changeable through core `ENV` variables.

You should [review this commit](https://github.com/ProcessMaker/processmaker/pull/4483/commits/e7157c8ed8c050d1d40cadef56639e3d3f0474cf?w=1) for additional customizations or opportunities to use new `ENV` variables. If you have a lot of customizations, you may undo this commit with `git revert e7157c8e` and make the [config file changes](https://github.com/laravel-shift/laravel-7.x/pull/2/commits/b6d066d9fa2b9482224f7b7332a3fa287e374924) manually.

**Comment by nolanpro** [comment]
:warning: Laravel 8 removed the `token` driver from the API authentication. This driver was not very robust and was removed from the documentation. Laravel now recommends using [Sanctum](https://laravel.com/docs/8.x/sanctum).

However, you may continue use the `token` driver and migrate to _Sanctum_ at your convenience.

**Comment by nolanpro** [comment]
:information_source: Shift [updated your dependencies](https://github.com/ProcessMaker/processmaker/pull/4483/commits/931a081733ca8fbefc6be904a73933e058b4478a?w=1) for Laravel 8. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 8.

Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling any additional package incompatibilities.

**Comment by nolanpro** [comment]
:warning: PHPUnit 8 deprecated using `assertContains` and `assertNotContains` for strings. These assertions now only handle arrays or `Traversable` objects.

Shift attempted to convert these assertions where reliable, but detected additional uses you should review and, if the arguments are strings, convert them to the [new string assertion methods](https://phpunit.readthedocs.io/en/9.5/assertions.html#assertstringcontainsstring).

- [ ] tests/Feature/Api/OAuthTest.php
- [ ] tests/Feature/ExtendedPMQLTest.php
- [ ] tests/Feature/HideSystemCategoriesTest.php
- [ ] tests/Traits/SearchAutocompleteTraitTest.php

**Comment by nolanpro** [comment]
:x: Shift detected Vue components within your `resources` folder. Laravel Mix 6 extracted Vue support into its own feature flag.

You should update your `webpack.mix.js` and append the new `mix.vue()` call when building any Vue components. For example:

```js
mix.js('resources/js/app.js', 'public/js').vue();
```

**Comment by nolanpro** [comment]
:warning: Shift upgraded your NPM dependencies and scripts for Laravel Mix 6. You will need to run `npm install` locally to ensure your dependencies are up-to-date and compatible.

If you encounter any issues, be sure you have the latest LTS or stable version of Node installed. If the problem persists, review the [Update to Mix 6](https://laravel-mix.com/docs/6.0/upgrade) docs for any additional steps.

**Comment by nolanpro** [comment]
:warning: Laravel 8 now requires PHPUnit 9 which made some configuration changes to its config file. You may automate these changes by running `vendor/bin/phpunit --migrate-configuration` or comparing your `phpunit.xml` to the [Laravel 8 version](https://github.com/laravel-shift/laravel-8.x/blob/master/phpunit.xml) and merging any changes.

**Comment by nolanpro** [comment]
:information_source: Laravel 8 reintroduced the `app/Models` folder by default. This is an _optional_ change. Laravel and the `artisan` commands will automatically detect if you are using the `app/Models` folder or not.

If you wish to modernize your application to use the `app/Models` folder, you may run the [Namespace Models Shift](https://laravelshift.com/laravel-namespace-models) for free.

**Comment by nolanpro** [comment]
:warning: The paginator now uses [Tailwind](https://tailwindcss.com/) for its default styling in Laravel 8. If you wish to continue using Bootstrap, you should add the following snippet to the `boot` method of your `AppServiceProvider`:

```php
\Illuminate\Pagination\Paginator::useBootstrap();
```

**Comment by nolanpro** [comment]
:information_source: Laravel 8 supports running your PHPUnit tests in parallel. Depending on your system, this may decrease run times as much as 70%.

To run your tests in parallel, you may use the `php artisan test --parallel` command, or use the underlying `vendor/bin/paratest` runner.

**Comment by nolanpro** [comment]
:warning: Shift detected you are using a Laravel package like Horizon or Nova which may need to have its published assets regenerated after upgrading. Be sure to use `artisan` to _republish_ these assets as well as `php artisan view:clear` to avoid any errors.

**Comment by nolanpro** [comment]
:warning: Laravel 8.x has reached [end of life](https://laravelversions.com/). It no longer receives bug fixes. Shift recommends continuing to upgrade to the latest version (Laravel 9.x).

**Review by danloa — APPROVED** [review]
Tested:
```
Request List
    Search
Completed (tab)
forms (tab)
    print
Settings/auth
    Configure SAML
    Edit
    Saml Login
Task list
Cancel Task
Summary
Notifications
    Configure notifications
    Verify notifications
Designer
    Process
        Create
        Edit
        Archive, Restore
        Export
        Import
    Script
        Create
        Run
        Edit
        Delete
    Screen
        Create
        Update
        Export
        Import
        Delete
    Env. Variable
       Create
        Update
        Delete
    Signals
        Create
        Update
        Delete
    User
        Create
        Update
        Delete
        Assign/Unassing group
        Assign permissions
        Edit Profile
    Group
        Create
        Update
        Delete
        Assign/Unassing user
        Assign permissions
    Settings
        Email
        SCIP
        SSO
    AUth clients
        Crete
        Update
        Delete
    UI
        Customize colors
    Script Executors
        Create
        Edit
        Delete
Saved Search
    Create
    Chart
    List 
    Delete
ABE
    Configure
    Use
Advanced User Manager
    User with Schedule
    Group Manager
    Process Manager
Collection
    Create 
    Edit
    Add Record
    Add Relation
    Remove Record
    Export 
    Import
    Remove Collection
Comment
    Configure process with comments
    Add comment
    Add reaction
Dynamic ui
    Create Dashboar
    Create Menu
    Assin dashcoard and menu to user
    Remove Dashboard
    Remove Menu
DocuSign:
    Configure
    Test in a process
Send Email
    Configure
    Test in a process
Translations
    Edit Translation
    Change user language
Versions
    List Versions
    Recover version
Vocabularies
    Create 
    Edit
    Delete  
    Assign to screen
Signature
    Create Signature
    Test executing a request
Documenter
     View documentation
Optimization
    Use in designer

**Review by ryancooley — APPROVED** [review]

**Pull request merged**
