### PR TITLE
Only show calcs button on form screens (4.1)

### PR DESCRIPTION
**Pull request by nolanpro**
https://github.com/ProcessMaker/processmaker/pull/4013 for 4.1

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-725-4-1-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-725-4-1-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-725-4-1-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-725-4-1-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-725-4-1-processmaker.ci.processmaker.net

**Review by danloa — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-725-4-1-processmaker.ci.processmaker.net

**Pull request merged**
