### PR TITLE
Bugfix/start events endpoint speed

### PR DESCRIPTION
**Pull request by caleeli**
This PR improves `api.processes.start` endpoint speed

- Improves `Process::getStartEvents`
- Add test to check the endpoint speed

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-start_events_endpoint_speed-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-start_events_endpoint_speed-processmaker.ci.processmaker.net

**Review by velkymx — APPROVED** [review]
Looks good!

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-start_events_endpoint_speed-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Pull request merged**
