### PR TITLE
FOUR-8540 - Process Map obtain additional information

### PR DESCRIPTION
**Pull request by eiresendez**
## Issue & Reproduction Steps

- A user can click on a BPMN element to display a pop-up window with relevant information.
- The process map should show a clear path of green connections for every task, event, and element that the request has executed, while every other element should be greyed out.

1. Create a process with multiple tasks and elements.
2. Generate a new request.
3. Go to the Overview tab.

## Solution

- The process map displays different visual indicators to differentiate between completed, in-progress, and unused BPMN elements for the request.
- Clicking on an element in the process map displays a pop-up window that makes an API call to retrieve relevant information about the node.

sample-color

## How to Test

- Please use the attached QA server or link the modeler in Core for manual testing.

## Related Tickets & Packages

- [FOUR-8540](https://processmaker.atlassian.net/browse/FOUR-8540)
- [FOUR-8888](https://processmaker.atlassian.net/browse/FOUR-8888)
- [Modeler's PR](https://github.com/ProcessMaker/modeler/pull/1585)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:modeler:feature/FOUR-8540
ci:deploy

[FOUR-8540]: https://processmaker.atlassian.net/browse/FOUR-8540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-8888]: https://processmaker.atlassian.net/browse/FOUR-8888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-8cd6855025.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-8cd6855025.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-8cd6855025.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-8cd6855025.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-8cd6855025.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-8cd6855025.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-8cd6855025.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-8cd6855025.eng.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Pull request merged**
