### PR TITLE
Correctly handle files in drafts

### PR DESCRIPTION
**Pull request by nolanpro**
## Issue & Reproduction Steps
See https://processmaker.atlassian.net/browse/FOUR-15242

When saving drafts, we didn't consider how to handle file uploads, which is a tricky process given our current file handling architecture.

## Solution
This PR associates files to a TaskDraft first. Only when the task is saved, it moves the files from TaskDraft to be associated with a ProcessRequest. There is also additional handling for deleting files in drafts.

This also solves a long standing issue in production. Previously, if a user edits a task and changes a file, but does not complete the task, the changed file is still saved in the processes request. This PR fixes that. If the user clear's their draft, the original file will be restored.

Also tested in web entry, even though web entry does not support drafts.

## How to Test
- Create a 2 task process with file upload, file download, and file previews. Check that clearing a task reverts to the original file.
- Test with web entry too.

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-15242
- REQUIRES
  - https://github.com/ProcessMaker/package-files/pull/124
  - https://github.com/ProcessMaker/screen-builder/pull/1582

ci:next
ci:deploy
ci:package-files:bugfix/FOUR-15242
ci:screen-builder:bugfix/FOUR-15242

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ac89e67f8d.engk8s.processmaker.net

**Review by danloa — COMMENTED** [review]
I'm getting some issues in my local environment tests:

1) In the first task, after I press "Clear Draft" a 404 error is displayed and printed in the console log
Peek 2024-04-26 09-13

2) In the second task an error is printed in the console (related to the FileUpload component)
image

**Review by gustavobascope — COMMENTED** [review]
1 If the form doesn't have a preview control when the task has a draft with a new file it doesn't show the draft filename

[Screencast from 26-04-24 10:28:18.webm](https://github.com/ProcessMaker/processmaker/assets/129873111/f5edc313-10a6-4e30-a819-407b7206525b)

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ac89e67f8d.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ac89e67f8d.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ac89e67f8d.engk8s.processmaker.net

**Review by gustavobascope — APPROVED** [review]
Approved
The draft data is restored and there isn't a console error

image

**Pull request merged**
