### PR TITLE
Fix Undefined 'Assignment' error when running email connector

### PR DESCRIPTION
**Pull request by sanjacornelius**
**Jira Ticket**

https://processmaker.atlassian.net/browse/FOUR-3423

<h2>Changes</h2>

- Add conditional to check if 'assignment' is set within the 'definition' object.

**Video**

https://user-images.githubusercontent.com/52755494/119534808-2c120d00-bd3c-11eb-80da-ced98821f0d6.mov

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3423-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3423-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3423-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3423-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3423-processmaker.ci.processmaker.net

**Review by ryancooley — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3423-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-19-processmaker.ci.processmaker.net

**Pull request merged**
