### PR TITLE
Prevent errors during validation break the screen builder loading

### PR DESCRIPTION
**Pull request by caleeli**
Fixes: https://processmaker.atlassian.net/browse/FOUR-3699

Safari does not support regular expressions with **lookbehind**. This was stored in the json definition of some screens in the inspector section.

https://caniuse.com/js-regexp-lookbehind

This PR prevents that errors during validation check break the screen builder loading

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3699-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3699-processmaker.ci.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3699-processmaker.ci.processmaker.net

**Pull request merged**
