### PR TITLE
FOUR-8342 Duplicate media queries

### PR DESCRIPTION
**Pull request by caleeli**
## Issue & Reproduction Steps
208 duplicate queries; not huge savings but unnecessary DB load If don't need avatar on every API query, don't append it
User:129

## Solution
- Convert `avatar` into a real column with URL of the avatar to avoid the query that constantly gets the avatar for each user every time an User is loaded.
- This URL is updated when the User profile is updated

## How to Test
- Download the branch with the change.
- Run the migrations
- Run the artisan command `php artisan users:populate-avatar`
- Test the Process Maker User Avatars, changing avatars, see the proper avatar is displayed in each place:
  - List of Processes
  - List of requests
  - Filters
  - Open Request
  - Open Task
  - Participants in Saved Searches

## Important step for CloudOps
- Run the migrations to add the avatar column
- Run the artisan command `php artisan users:populate-avatar` to populate with the current avatar URLs

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-8342

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Review by runyan-co — CHANGES_REQUESTED** [review]
Hey @caleeli, this looks great! The only change I'd recommend is adding a call to the new populate avatar command to an upgrade migration so it's called when upgrading to a new version. Would you be able to add that in?

**Comment by caleeli** [comment]
> Hey @caleeli, this looks great! The only change I'd recommend is adding a call to the new populate avatar command to an upgrade migration so it's called when upgrading to a new version. Would you be able to add that in?

Thanks @runyan-co for the feedback, the suggestion was implemented

**Review by runyan-co — CHANGES_REQUESTED** [review]
Hey @caleeli, thanks for the changes! I do believe we need to add them to an [_upgrade migration_ specifically](https://github.com/ProcessMaker/processmaker/blob/develop/upgrades/2022_04_19_164837_sanitize_usernames.php), which you can generate an empty one to use just like a regular migration (`php artisan make:upgrade`).  Do ignore the `$to` property as it was deprecated in the upgrade migrations. Let me know if I can answer any questions about this! 👍🏻

**Comment by nolanpro** [comment]
@caleeli @runyan-co I also think its a good idea to only have migrations in the migrations folder. If we ever want to squash migrations to improve performance (`php artisan schema:dump --prune`), having artisan commands in there would make that difficult.

I realize we already do it in older migration files but I think it would be good practice going forward to only have DB migrations (that can be directly converted to SQL) in the migrations folder.

**Comment by runyan-co** [comment]
> @caleeli @runyan-co I also think its a good idea to only have migrations in the migrations folder. If we ever want to squash migrations to improve performance (`php artisan schema:dump --prune`), having artisan commands in there would make that difficult.
> 
> I realize we already do it in older migration files but I think it would be good practice going forward to only have DB migrations (that can be directly converted to SQL) in the migrations folder.

I agree completely @nolanpro, the upgrade migration should only contain the call to the `users:populate-avatar` artisan command without any schema changes. This was a feature we specifically designed to do this type of thing since standard migrations are meant for db/schema related changes.

**Review by runyan-co — APPROVED** [review]

**Review by nolanpro — APPROVED** [review]

**Review by ryancooley — APPROVED** [review]

**Pull request merged**
