### PR TITLE
FOUR-2891: Thrown signal to contain the data from the throwing process

### PR DESCRIPTION
**Pull request by danloa**
Fixes [https://processmaker.atlassian.net/browse/FOUR-2891](https://processmaker.atlassian.net/browse/FOUR-2891)

Signal throw events (intermediate and end) have a new inspector to configure the signal's payload content. One of these options allows to set an expression for the payload, this expression can be a "burned" value or it can be something like first_name ~ "  " ~ last_name (using the expression language used by the system)
image

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2891-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2891-processmaker.ci.processmaker.net

**Review by caleeli — APPROVED** [review]
Very Nice Code!

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2891-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Pull request merged**
