### PR TITLE
New helper added

### PR DESCRIPTION
**Pull request by CarliPinell**
## Issue & Reproduction Steps

New Helper created to convert stdClass Object to Array

## Related Tickets & Packages
- FOUR-8255

## Code Review Checklist
- [x] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [x] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [x] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [x] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [x] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [x] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [x] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [x] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy

### CODE REVIEW

**Review by luNunezProcessmaker — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-c13427794e.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-c13427794e.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-c13427794e.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-c13427794e.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-c13427794e.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-c13427794e.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-c13427794e.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-c13427794e.eng.processmaker.net

**Pull request closed without merging**
