### PR TITLE
FOUR-14693

### PR DESCRIPTION
**Pull request by pmPaulis**
## Issue & Reproduction Steps
404 Error in SSO Integrations in Admin Settings 

## Solution
- Use id instead of name

## How to Test

- Log in PM4
- Go to Admin Settings
- Click on SSO
- Enable any Integration like facebook

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-14693

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy

### CODE REVIEW

**Review by fagubla — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ad9fac79c1.engk8s.processmaker.net

**Review by ana-mauricio — CHANGES_REQUESTED** [review]
The content to SSO connections is not visible . It is empty
image
@pmPaulis

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ad9fac79c1.engk8s.processmaker.net

**Comment by pmPaulis** [comment]
> The content to SSO connections is not visible . It is empty image @pmPaulis

@ana-mauricio 
this was fixed 
image

**Review by ana-mauricio — APPROVED** [review]

**Pull request merged**
