### PR TITLE
Fix case in backend validation messages

### PR DESCRIPTION
**Pull request by nolanpro**
Fixes http://tickets.pm4overflow.com/tickets/498

image

### CODE REVIEW

**Review by danloa — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-498-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-498-processmaker.ci.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-498-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Pull request merged**
