### PR TITLE
Prevent submitting a task multiple times

### PR DESCRIPTION
**Pull request by nolanpro**
https://github.com/ProcessMaker/processmaker/pull/3897 for 4.1.21

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3631-for-4-1-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3631-for-4-1-processmaker.ci.processmaker.net

**Review by ryancooley — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3631-for-4-1-processmaker.ci.processmaker.net

**Pull request merged**
