### PR TITLE
Search nested json for self-serve groups and users

### PR DESCRIPTION
**Pull request by nolanpro**
See https://github.com/ProcessMaker/processmaker/pull/3903

This brings the change to 4.1

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3647-for-4-1-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3647-for-4-1-processmaker.ci.processmaker.net

**Review by caleeli — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3647-for-4-1-processmaker.ci.processmaker.net

**Pull request merged**
