### PR TITLE
Setting prop "options" to an object is deprecated. Use the array format instead

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
Fixes [ticket 499](http://tickets.pm4overflow.com/tickets/499)

- change options in props

### CODE REVIEW

**Review by ryancooley — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-499-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-499-processmaker.ci.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-499-processmaker.ci.processmaker.net

**Pull request merged**
