### PR TITLE
Script error using getProcesses API endpoint

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
## Issue & Reproduction Steps
The following error is generated when we query the getProcesses() endpoint in Scripts:

`(Code: 0) Warning: settype(): Invalid type in /opt/sdk-php/lib/ObjectSerializer.php on line 335 Warning: settype(): Invalid type in /opt/sdk-php/lib/ObjectSerializer.php on line 335`

## Solution
- Change response field self_service_tasks of array to object

## How to Test
1. Create process with assigment self-service
2. Create a new PHP script
3. the scrAdd the following code and run:

`$apiInstance = $api->processes();
$result = $apiInstance->getProcesses();
return ['processes' => $result];`

## Related Tickets & Packages
[FOUR-5377](https://processmaker.atlassian.net/browse/FOUR-5377)

## Code Review Checklist
- [x] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [x] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [x] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [x] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [x] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [x] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5377-4-2-processmaker.ci.processmaker.net

**Review by agustinbusso — APPROVED** [review]
Working well with processes that have self_service assignment. You should rebuild PHP script executor:

Screen Shot 2022-03-16 at 12 51 04

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5377-4-2-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-5377-4-2-processmaker.ci.processmaker.net

**Review by ryancooley — APPROVED** [review]

**Pull request merged**
