### PR TITLE
Change script execution response notification to script response event

### PR DESCRIPTION
**Pull request by caleeli**
Fixes: http://tickets.pm4overflow.com/tickets/331

This PR includes:

- changes script response notification by script response event.
- update the script execution tests
- increase the default horizon processes to run jobs

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-331-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-331-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-331-processmaker.ci.processmaker.net

**Review by danloa — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-331-processmaker.ci.processmaker.net

**Pull request merged**
