### PR TITLE
FOUR-2223: Translations Update - C

### PR DESCRIPTION
**Pull request by danloa**
As part of [https://processmaker.atlassian.net/browse/FOUR-2223](https://processmaker.atlassian.net/browse/FOUR-2223)

### CODE REVIEW

**Review by GooseCoder — APPROVED** [review]
LGTM approved

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2223-c-processmaker.ci.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2528-processmaker.ci.processmaker.net

**Pull request merged**
