### PR TITLE
FOUR-13490 | Design and Implement the Dropdown for Selecting the Type of Screen

### PR DESCRIPTION
**Pull request by mcraeteisha**
# Feature
Tickets: [FOUR-13490](https://processmaker.atlassian.net/browse/FOUR-13490) & [FOUR-13494](https://processmaker.atlassian.net/browse/FOUR-13494)

As a Designer, I want to find an easy, simple, and visual way to select the type of screen, name it, and add a template if needed.

- Select “+ Screen”
- A renewed modal opens where the user can see:
	- A drop-down with the type of screen (form, display, email, conversational)
	- The following fields are available on the right side of the screen: 
		- Name
		- Description
		- Category
		- Project

# How to Test
1. Go to branch `subtask/FOUR-13490` in `processmaker`.
2. Go to Designer → Screens.
3. Click on `+SCREEN`.
4. The modal should include a dropdown for users to select their Screen Type. This should match the [Figma mockup](https://www.figma.com/file/Tr2bVMtC4jr6KGWBvM6Vtp/Spring-24?type=design&node-id=10066-83443&mode=design&t=OHEapWuj9BBZzbXz-0).
5. The modal should include fields for 'Name', 'Description', 'Category', and 'Project' on the right.

ci:next
ci:deploy

# Code Review Checklist

- [ ]  I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ]  This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ]  This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ]  This solution fixes the bug reported in the original ticket.
- [ ]  This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ]  This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ]  This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ]  This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ]  This ticket conforms to the PRD associated with this part of ProcessMaker.

[FOUR-13490]: https://processmaker.atlassian.net/browse/FOUR-13490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FOUR-13494]: https://processmaker.atlassian.net/browse/FOUR-13494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by sanjacornelius** [comment]
Looks great @mcraeteisha just a few observations:

1. Lets confirm with Claudia the proper descriptions for each of the screen types
2. Design Observations:
Screenshot 2024-03-06 at 10 59 19 AM

**Comment by sanjacornelius** [comment]
@mcraeteisha I am also unable to create a screen. 


Uploading Screen Recording 2024-03-06 at 11.45.39 AM.mov…

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-b042c5b0ca.engk8s.processmaker.net

**Review by sanjacornelius — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-b042c5b0ca.engk8s.processmaker.net

**Pull request merged**
