### PR TITLE
Request screen printer is loading faster than the page is rendering

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
Fixes [FOUR-2522](https://processmaker.atlassian.net/browse/FOUR-2522)

- add overlay to page to print

https://user-images.githubusercontent.com/1747025/125529201-8f15a445-d9e0-4db0-8cfb-a9977b256a2c.mp4

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2522-b-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2522-b-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2522-b-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2522-b-processmaker.ci.processmaker.net

**Review by nolanpro — CHANGES_REQUESTED** [review]
@marcoAntonioNina can we use the bootstrap vue overlay for this? https://bootstrap-vue.org/docs/components/overlay

**Comment by marcoAntonioNina** [comment]
@nolanpro change made

**Review by nolanpro — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2522-b-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2522-b-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2522-b-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2522-b-processmaker.ci.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2522-b-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Pull request merged**
