### PR TITLE
Emit input event from ColumnChooser

### PR DESCRIPTION
**Pull request by ryancooley**
## Changes
- Emits an update event from the Column Chooser component so that changes can be detected in other components

## Required By
- https://github.com/ProcessMaker/package-collections/pull/277

## Tickets
- http://tickets.pm4overflow.com/tickets/285
- https://processmaker.atlassian.net/browse/FOUR-3769

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3769-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3769-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3769-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3769-processmaker.ci.processmaker.net

**Review by marcoAntonioNina — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3769-processmaker.ci.processmaker.net

**Pull request merged**
