### PR TITLE
Improvement/kr 7853

### PR DESCRIPTION
**Pull request by Cievoloth**
Solution to Sauce labs issue:

the code does the following 
1.- lower case  the branch names 'cause upper cases make the process have errors
2.- Temporally copy the app to deploy in QA environment so Dusk can access to it
3. - after all test have passed the temporal folder is eliminated

@alvarofloresPM

### CODE REVIEW

**Comment by velkymx** [comment]
@Cievoloth you have Conflicts ;)

**Comment by Cievoloth** [comment]
Done!! 
it was conflicting with some commented lines (dusk automation part) that someone added

Regards

@alvarofloresPM

**Comment by velkymx** [comment]
@caleeli Dusk tests all blow up. ;) We feel your pain.

**Comment by velkymx** [comment]
I'm investigating this migration error.

**Pull request merged**
