### PR TITLE
Bugfix/fix failing tests 4/2

### PR DESCRIPTION
**Pull request by caleeli**
- Restore missing ManualTask declaration
- Fix Self service tests

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-fix_failing_tests_4-2-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-fix_failing_tests_4-2-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-fix_failing_tests_4-2-processmaker.ci.processmaker.net

**Review by sanjacornelius — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-fix_failing_tests_4-2-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Pull request merged**
