### PR TITLE
Fix duplicated option in Assignment

### PR DESCRIPTION
**Pull request by caleeli**
Resolves: http://tickets.pm4overflow.com/tickets/488

Fix duplicated option in Assignment.

duplicated-key1

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-488-processmaker.ci.processmaker.net

**Review by nolanpro — CHANGES_REQUESTED** [review]
@caleeli if you don't change the "start as" it sets it to administrator, not anonymous. It only gets set to anonymous if you change it and change it back. See video:
Kapture 2021-03-08 at 14 01 32

**Comment by caleeli** [comment]
@nolanpro thanks for the comment, I fixed the default value

**Review by nolanpro — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-488-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-488-processmaker.ci.processmaker.net

**Pull request merged**
