### PR TITLE
Only show calcs button on form screens (4.2)

### PR DESCRIPTION
**Pull request by nolanpro**
Fixes http://tickets.pm4overflow.com/tickets/725

Removes the Calcs button on the screen builder for any type other than forms

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-725-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-725-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-725-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-725-processmaker.ci.processmaker.net

**Review by danloa — APPROVED** [review]

**Pull request merged**
