### PR TITLE
Update Screen Sync Command to Support Refined File Structure

### PR DESCRIPTION
**Pull request by sanjacornelius**
## Issue & Reproduction Steps
This PR updates the screen sync command `php artisan processmaker:sync-guided-templates` to support the refined file structure of the `screen-template` GitHub repository. Additionally, it adds support for displaying the template thumbnail and preview thumbnail.

.

## Solution

- Dynamically set specific template details from the exported screen template payload, such as `screen_type` and `screen_custom_css`.
- Properly handle the displaying of the `thumbnail` and `previewThumbs` media in the Create Screen Modal.

## How to Test

1. Run the command php artisan processmaker:sync-guided-templates.
2. Verify that the command synchronizes the screen templates correctly, including their updated file structure.
3. Open the Create Screen Modal and confirm that the template thumbnail and preview thumbnails are displayed properly.

## Related Tickets & Packages
- [FOUR-14508](https://processmaker.atlassian.net/browse/FOUR-14508)

ci:next
ci:deploy

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

[FOUR-14508]: https://processmaker.atlassian.net/browse/FOUR-14508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-42af8f4aa6.engk8s.processmaker.net

**Review by estebangallego — APPROVED** [review]
Works as expected

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-42af8f4aa6.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-42af8f4aa6.engk8s.processmaker.net

**Pull request merged**
