### PR TITLE
FOUR-13090 Close active sessions when Block duplicate session is activated 

### PR DESCRIPTION
**Pull request by caleeli**
## Issue & Reproduction Steps
The already duplicated active sessions are still active when **Block duplicate session** is activated.

## Solution
- Close active sessions when Block duplicate session is activated .

## How to Test

- Log in
- Create a new user
- Log in with new user in diferent browser (in a same IP)
- From admin user configure Block duplicate session in IP Restriction
- Go to Admin tab
- Go to settings option in sidebar menu
- Go to Session Control tab
- Go to IP Restriction and edit
- Enable Block duplicate session
- Click on save button

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-13090

## Code Review Checklist
- [x] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [x] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [x] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [x] This solution fixes the bug reported in the original ticket.
- [x] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [x] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [x] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [x] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [x] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next
ci:deploy

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-06c26078fa.eng.processmaker.net

**Review by julceslauhub — APPROVED** [review]
Approved

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ff31518069.engk8s.processmaker.net

**Review by devmiguelangel — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-ff31518069.engk8s.processmaker.net

**Pull request merged**
