### PR TITLE
Remove base_64 encode for import/export

### LINKED ISSUE #1923: Export - Remove Base64 Encoding
All exports should be .json files with unencrypted json

### PR DESCRIPTION
**Pull request by caleeli**
Resolves #1923 

This PR includes:

- Removes the base_64 encode/decode for Import/Export of files (process and screens)
- Add a validation to check the file structure
- Additional unit tests to check the validation with: json, base64, any text file, any binary file

image

### CODE REVIEW

**Comment by velkymx** [comment]
@caleeli change the file name to be: processname-type-processmaker4.json

ex: pet-adoption-process-processmaker4.json
ex: choose-a-home-screen-processmaker4.json

**Comment by PMQABen** [comment]
So if someone tries to import an existing spark file that's b64 encoded, it's gonna break huh?

**Comment by velkymx** [comment]
@caleeli we should still import spark files (even if temporarily) to make it easier on QA / Sales to use the import functionality. We will remove it later.

**Comment by caleeli** [comment]
@velkymx @PMQABen A file import validation was added to check if the file is a valid json or base64 with the right structure.

**Pull request merged**
