### PR TITLE
FOUR-13156: It is to possible save the configuration on the process with description empty from LaunchPad.

### PR DESCRIPTION
**Pull request by CarliPinell**
## How to Test
-  Open Any Process with "Open in Launchpad"
- Clear description field
- Try to save (Modal window won`t close until description is entered)
- Close modal window
- Open again Edit in Launchpad, previous Descrition is shown

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-13156

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.
ci:deploy
ci:next

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-5a123785f3.engk8s.processmaker.net

**Comment by pmPaulis** [comment]
@CarliPinell 
this is not working from the ellipsis in launchpad
image

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-5a123785f3.engk8s.processmaker.net

**Review by fagubla — APPROVED** [review]

**Comment by pmPaulis** [comment]
I tested in modeler:
image
I tested in Launchdapd
image

The second is not working

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-5a123785f3.engk8s.processmaker.net

**Pull request merged**
