### PR TITLE
observation/FOUR-13416 points button is over the table header

### PR DESCRIPTION
**Pull request by gustavobascope**
## Issue & Reproduction Steps
points button is over the table header

## Solution
fix ellipsis position

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-13416
https://processmaker.atlassian.net/browse/FOUR-13967

ci:deploy
ci:next

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-093db323db.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-093db323db.engk8s.processmaker.net

**Comment by CarliPinell** [comment]
The issue has been resolved. I Attach as video a small test to verify everythnig is working fine:

https://github.com/ProcessMaker/processmaker/assets/131476081/7af8f547-1567-42dc-bb1a-c97be97a007a

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-093db323db.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-093db323db.engk8s.processmaker.net

**Pull request merged**
