### PR TITLE
FOUR-15510: [Summer24] Actions By Email V2

### PR DESCRIPTION
**Pull request by pmPaulis**
## Issue & Reproduction Steps
**Increased user engagement**: Users are more likely to stay engaged with the system when they receive timely notifications about relevant activities.
**Improved responsiveness**: Users can promptly respond to important updates or tasks, enhancing overall efficiency.
**Enhanced user experience**: Providing email notifications seeking to respond to tasks directly from the email to avoid the user having to access ProcessMaker.

## Prd
https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3341647873/Actions+by+Email+V2

## Figma
https://www.figma.com/design/RiBfT37iExrySseqYZuLg3/Summer-2024?node-id=103-17&t=EZjsN3lxFW9jiFGb-0

## Solution
- New controls was created in the Email Screen
- New configuration in the Task -> Email Notification
- Configure Action by email for a task
- Create a request

## How to Test
- Create a new Email Screen
- We can use a new control **Submit button**

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-15510

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next
ci:screen-builder:feature/FOUR-15510
ci:connector-send-email:feature/FOUR-15510
ci:processmaker-bpmn-moddle:feature/FOUR-15510

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-75e4dbb76a.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-75e4dbb76a.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-75e4dbb76a.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-75e4dbb76a.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-75e4dbb76a.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-75e4dbb76a.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-75e4dbb76a.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-75e4dbb76a.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-75e4dbb76a.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-75e4dbb76a.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-75e4dbb76a.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-75e4dbb76a.engk8s.processmaker.net

**Review by fagubla — APPROVED** [review]

**Pull request closed without merging**
