### PR TITLE
FOUR-13376:Type of letter of the square’s title are not the same as figma in Designer Welcome Screen

### PR DESCRIPTION
**Pull request by fagubla**
## Issue & Reproduction Steps
The Type of letter of the section’s title don’t look the same as Figma:

## Solution
- Apply the same styles defined in figma

## How to Test
Login and Go to Designer

## Related Tickets & Packages
- [FOUR-13376](https://processmaker.atlassian.net/browse/FOUR-13376)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:next

[FOUR-13376]: https://processmaker.atlassian.net/browse/FOUR-13376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-86def28732.engk8s.processmaker.net

**Review by pmPaulis — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-86def28732.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-86def28732.engk8s.processmaker.net

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-86def28732.engk8s.processmaker.net

**Pull request merged**
