### PR TITLE
Fix trigger boundary events with multi-instance subprocess

### PR DESCRIPTION
**Pull request by caleeli**
## Issue & Reproduction Steps
Fix trigger boundary events with multi-instance subprocess.

## Solution
- Fix Job that catch signal.
- Fix missing signal_events property in process_request table when a boundary event is activated.

## How to Test
- Create A Collection
- Add records to the collection
- Enable the Collection events
- Import or create a process similar to the attached one
- Assign to the boundary signal event to one of the events of the collection
- Start the process
- Trigger one of the collection events
- The CallActivity should be closed and continue to the task that follows the boundary event

https://user-images.githubusercontent.com/8028650/144326886-c72baa1b-121a-46a9-b8d4-3864a222080e.mp4

Main Process:
[Signals.json.txt](https://github.com/ProcessMaker/processmaker/files/7637564/Signals.json.txt)
Sub Process:
[subprocess.json.txt](https://github.com/ProcessMaker/processmaker/files/7637565/subprocess.json.txt)
Collection:
[persons.json.txt](https://github.com/ProcessMaker/processmaker/files/7637572/persons.json.txt)

## Related Tickets & Packages
- [FOUR-4407](https://processmaker.atlassian.net/browse/FOUR-4407)

Requires: https://github.com/ProcessMaker/nayra/pull/212
Requires: https://github.com/ProcessMaker/package-collections/pull/293

## Limitation
The case in which a multi-instance parallel subprocess that triggers immediately multiple times the same signal is not yet working as expected in PM4 Core, seems it will need some additional work in the Extended CallActivity class.

This Escenario is working in Nayra stand-alone.
Main process:
image
Sub process:
image

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Comment by caleeli** [comment]
Note: This requires the nayra updates to pass the tests

**Comment by nolanpro** [comment]
@caleeli I'm running into an issue where the process does not complete if you complete one of the loop tasks before the signal is caught. See the test I added 'testBoundryLoop' to tests/Feature/Api/TriggerSignalInRequestTest.php

**Review by danloa — CHANGES_REQUESTED** [review]
While testing, if the boundary condition is always true, n instance are still created. Looking at the bpm 2 documentation it seems that just one instance should be created (because the interrupt it is immediately triggered)

**Comment by caleeli** [comment]
@nolanpro the test case you reported is now fixed.
image

@danloa the process example you reported is now fixed.
image

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-4407-b-processmaker.ci.processmaker.net

**Review by danloa — APPROVED** [review]

**Pull request merged**
