### PR TITLE
Updates for multi-file screen controls

### PR DESCRIPTION
**Pull request by nolanpro**
Part of https://github.com/ProcessMaker/screen-builder/pull/1113

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-4406-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-4406-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-4406-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-4406-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-4406-processmaker.ci.processmaker.net

**Review by danloa — APPROVED** [review]

**Review by marcoAntonioNina — APPROVED** [review]

**Pull request merged**
