### PR TITLE
FOUR-8538 - Highlight request's path on Process Map

### PR DESCRIPTION
**Pull request by eiresendez**
## Issue & Reproduction Steps

As a user, I want to visualize the path that the request took to reach its current state to understand the history and status of the request.

1. Create a process with multiple tasks, you may include gateways.
2. Initiate a new request.
3. Proceed to complete the process and view the Process Map in the Overview Tab.
4. You should be able to differentiate between a completed task, a task in progress, and unused BPMN elements.

## Solution
- We get a list of completed and in-progress nodes.
  - That list is sent to the modeler to apply the appropriate highlight to the node.
- We added the Map Legend.
- Also, according to a comment by Jose Maldonado. The Overview tab was moved right next to the Tasks tab instead of leaving it at the end. It's probably a good idea to have the Overview as the first tab, but that can be changed later.
- Added feature of clicking on a node/shape and display the popup (only UI) that will show relevant information in the future.
- Implement loading state for iframe to avoid weird borders in Chrome and improve the user experience by providing visual feedback during iframe loading. 

highlighted-path

## How to Test
- Please link modeler and core or use the QA test server.

## Related Tickets & Packages
- [FOUR-8538](https://processmaker.atlassian.net/browse/FOUR-8538)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:modeler:feature/FOUR-8538
ci:deploy

[FOUR-8538]: https://processmaker.atlassian.net/browse/FOUR-8538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-6f660955be.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-6f660955be.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-6f660955be.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-6f660955be.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-6f660955be.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-6f660955be.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-6f660955be.eng.processmaker.net

**Review by gustavobascope — APPROVED** [review]
I don't have observations. 
image

**Review by nolanpro — CHANGES_REQUESTED** [review]
@eiresendez Looks good! I noticed this:

Sometimes it loads with these weird borders:
image

It seems to be about 50% of the time I reload the page then click the overview tab. Have you seen this behavior locally? Unfortunately I can't test on the testing server right now so this is local (chrome, mac)

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-6f660955be.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-6f660955be.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-6f660955be.eng.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Pull request merged**
