### PR TITLE
Add FileDownload component for display form type

### PR DESCRIPTION
**Pull request by chipit24**
This PR fixes an issue with the FileDownload component for display type forms.

How to test:
Drag a FileDownload component into the form builder in a display form type. The FileDownload should render and you should not see an `unknown custom element "FileDownload" ...` error in the console anymore.

### CODE REVIEW

**Comment by chipit24** [comment]
Running the dusk tests locally, I don't get any errors:
```console
PHPUnit 7.5.9 by Sebastian Bergmann and contributors.

SSS.....SSS                                                       11 / 11 (100%)

Time: 1.4 hours, Memory: 30.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 11, Assertions: 16, Skipped: 6.
```

On the CI, the tests which are showing as failing seem to be the skipped tests above. The tests seem to be failing on the login screen, `Unable to locate element: {"method":"css selector","selector":"body textarea[name='input[name=username]']"}`.

I also ran the tests on `develop` and I get the same results as on this branch. And when I look at another passing test on another CI run, it shows the same results as I'm getting locally. So I think the test is just being flaky when run on the CI. @velkymx are you able to re-run the tests on CircleCI manually?

**Comment by ZLTM** [comment]
Working here

**Comment by velkymx** [comment]
@chipit24 let me know when this is ready to be merged.

**Comment by chipit24** [comment]
Seems I accidentally closed this, but it looks like this branch was already merged into `develop` through `feature/2025`, but the `Vue.component` line was omitted.

@velkymx I opened a new PR for this here: https://github.com/ProcessMaker/processmaker/pull/2062.

**Pull request closed without merging**
