### PR TITLE
feature/FOUR-9486: IT6 Default Welcome Screens final

### PR DESCRIPTION
**Pull request by pmPaulis**
## Issue & Reproduction Steps
This is a feature defined in the document: https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3123380225/Default+Welcome+Screens

## Solution
Implement the following user stories:

**Home**
- As a Participant, I want quick and convenient access to my personal **To-Do list** (Open tasks assigned to me) so that I can easily manage and track my tasks.
- As a Participant, I want to have quick and effortless access to **My Requests** (created by me), allowing me to stay informed about their status and take necessary actions promptly.
- As a Participant, I want to have quick and convenient access to the option of making a **New Request**, allowing me to easily start a Process.

**Designer**
- As a Designer, I want quick and convenient access to create a new asset, enabling me to efficiently design and contribute to the process repository.

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-9486

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

## Environment Fall
ci:deploy
ci:next
ci:screen-builder:feature/FOUR-9486
ci:package-projects:feature/FOUR-9486
ci:package-dynamic-ui:feature/FOUR-9486

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0e373669aa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0e373669aa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0e373669aa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0e373669aa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0e373669aa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0e373669aa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0e373669aa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0e373669aa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0e373669aa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0e373669aa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0e373669aa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0e373669aa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0e373669aa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0e373669aa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0e373669aa.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0e373669aa.eng.processmaker.net

**Review by luNunezProcessmaker — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-0e373669aa.eng.processmaker.net

**Review by fagubla — APPROVED** [review]

**Pull request merged**
