### PR TITLE
ticket 487: If a scheduled task fails the rest of the queue is not executed.

### PR DESCRIPTION
**Pull request by danloa**
Fixes [http://tickets.pm4overflow.com/tickets/487](http://tickets.pm4overflow.com/tickets/487)

- Adds a catch/try block for every processed task so if one fails the next ones are still executed
- When a task fails contextual information of the task is logged.

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-487-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-487-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-487-processmaker.ci.processmaker.net

**Review by caleeli — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-487-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Pull request merged**
