### PR TITLE
Group Manager available with advanced-users package

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
Fixes [ticket-672](http://tickets.pm4overflow.com/tickets/672)

- Move component to package advanced-users

### CODE REVIEW

**Review by danloa — CHANGES_REQUESTED** [review]
Even if the package is not installed:

1. The column manager_id is added to the groups table
2. Users are created and assigned as managers of the default PM groups (administrators, requesters, etc.)

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-672-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-672-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-672-processmaker.ci.processmaker.net

**Review by danloa — APPROVED** [review]

**Review by nolanpro — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-672-processmaker.ci.processmaker.net

**Pull request merged**
