### PR TITLE
Make sure Tool Tip to view collections displays View Collection

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
Fixed [FOUR-3376](https://processmaker.atlassian.net/browse/FOUR-3376)

- Change label delete to view collection in list signal of collection

signalViewCollection

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3376-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3376-processmaker.ci.processmaker.net

**Review by sanjacornelius — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3376-processmaker.ci.processmaker.net

**Pull request merged**
