### PR TITLE
JointJS version should be resolved by Modeler

### PR DESCRIPTION
**Pull request by caleeli**
## Issue & Reproduction Steps
JointJS version is different to the Modelers JoinJS version.

1. See the process below
2. Connect a DataObject or DataStore to a Task
3. An validation error is thrown

image

**Expected behavior:** 
Throw validation errors.

**Actual behavior:** 
No validation errors should be catch when a DataObject/DataStore is connected to a Task.

## Solution
- Fix validation rules: ID is not required for input output specification nodes (Requires: https://github.com/ProcessMaker/bpmnlint-plugin/pull/20)
- JointJS version should be solved by Modeler

## How to Test
Create a process like this:
image

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-5102
- https://github.com/ProcessMaker/bpmnlint-plugin/pull/20
- https://github.com/ProcessMaker/modeler/pull/1425

## Code Review Checklist
- [x] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [x] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [x] This solution fixes the bug reported in the original ticket.
- [x] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [x] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [x] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [x] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [x] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://four-5102-fix-processmaker.ci.processmaker.net

**Review by eiresendez — CHANGES_REQUESTED** [review]
Hi @caleeli , when removing that dependency and running `npm run dev/watch` I get the error "This dependency was not found: * jointjs" but if I remove `jointjs` from `webpack.mix.js` it works fine. What do you think?

image

**Review by eiresendez — APPROVED** [review]

**Review by eiresendez — APPROVED** [review]
It works as expected! 

https://user-images.githubusercontent.com/90741874/151883503-d31b2c54-5781-4d91-9401-117f74e0f5de.mov

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://four-5102-fix-processmaker.ci.processmaker.net

**Review by ryancooley — APPROVED** [review]

**Pull request merged**
