### PR TITLE
Feature/FOUR-13096 New table styles to process list

### PR DESCRIPTION
**Pull request by gustavobascope**
## Issue & Reproduction Steps
New table styles to process list

## Solution
styling of the process table

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-13096

ci:deploy
ci:next

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-78f3f6b23a.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-78f3f6b23a.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-78f3f6b23a.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-78f3f6b23a.eng.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-78f3f6b23a.eng.processmaker.net

**Comment by ryancooley** [comment]
@gustavobascope Please review and fix the [SonarQube issues](https://sonarqube.processmaker.net/dashboard?id=ProcessMaker_processmaker_AYkzkfKexYvY_isvKt07&pullRequest=5926) listed here.

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-78f3f6b23a.eng.processmaker.net

**Pull request merged**
