### PR TITLE
[SPRING] observation/FOUR-14686 Save Draft does not work when a Task was opened

### PR DESCRIPTION
**Pull request by gustavobascope**
## Issue & Reproduction Steps
Save Draft does not works when a Task was opened

## Solution
Added new autosave validation for new tasks

## Related Tickets & Packages
https://processmaker.atlassian.net/browse/FOUR-14686

ci:deploy
ci:next

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a58157bfc8.engk8s.processmaker.net

**Review by nolanpro — CHANGES_REQUESTED** [review]
@gustavobascope I dont think this is going to work. If a script task runs before this, all the values of the script task will be included in the draft. `const screenFields = @json($screenFields);` comes from from the initial load, same as `const task = @json($task);` but since it's from a start event, there are no screen fields yet. Once the interstitial is done, we have a new Task but we are not updating the screenFields variable.

I think we should change screenFields to a `var` instead of a const, and updating it when the task changes.

**Comment by gustavobascope** [comment]
> @gustavobascope I dont think this is going to work. If a script task runs before this, all the values of the script task will be included in the draft. `const screenFields = @json($screenFields);` comes from from the initial load, same as `const task = @json($task);` but since it's from a start event, there are no screen fields yet. Once the interstitial is done, we have a new Task but we are not updating the screenFields variable.
> 
> I think we should change screenFields to a `var` instead of a const, and updating it when the task changes.

Fixed observations

**Comment by tokensPM** [comment]
QA server K8S was successfully deployed https://ci-a58157bfc8.engk8s.processmaker.net

**Review by nolanpro — APPROVED** [review]

**Pull request merged**
