### PR TITLE
Review Create Process text below Name, we say The process must be distinct, do we mean unique?

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
Fixes [ticket 514](http://tickets.pm4overflow.com/tickets/514)

- change in forms create/edit Process, Screen, scripts, categories, environment variables, auth clients

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-514-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-514-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-514-processmaker.ci.processmaker.net

**Review by ryancooley — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://4-1-21-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-ticket-514-processmaker.ci.processmaker.net

**Pull request merged**
