### PR TITLE
When redirecting to a task, only look for active user tasks

### PR DESCRIPTION
**Pull request by nolanpro**
Fixes https://processmaker.atlassian.net/browse/FOUR-2875

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2875-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2875-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2875-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2875-processmaker.ci.processmaker.net

**Review by sanjacornelius — APPROVED** [review]

**Review by caleeli — APPROVED** [review]
Perfect!

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-2875-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Pull request merged**
