### PR TITLE
Comment Skipped Tasks

### PR DESCRIPTION
**Pull request by caleeli**
Requires: (Nayra update) https://github.com/ProcessMaker/nayra/pull/196

This PR add comments for skipped tasks

image

### CODE REVIEW

**Review by nolanpro — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3023-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3023-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3023-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Pull request merged**
