### PR TITLE
Ticket 660: Process status new ARCHIVED status (For 4.2)

### PR DESCRIPTION
**Pull request by agustinbusso**
Ticket [http://tickets.pm4overflow.com/tickets/660](http://tickets.pm4overflow.com/tickets/660)
- Added new field ARCHIVED to processes
- Move all actual INACTIVE processes to ARCHIVED
- Added dropdown field on import screen to allows set ACTIVE or INACTIVE process status by default when importing
- Added dropdown field on config screen to allows change ACTIVE or INACTIVE process status
- List both ACTIVE and INACTIVE processes on process listing view and list ARCHIVED processes on ARCHIVED (instead INACTIVE)
- Added new icons on UI to display current status (ACTIVE, INACTIVE) (See attached image)
- Moved warnings icon to left of name of process (See attached image)
- Added validations on Conditional events, Signal events and Timer events to only trigger an event when process status is ACTIVE
- Added signal event test 
    - Signal event must triggered when process is ACTIVE
    - Signal event must not triggered when process is INACTIVE
- Added conditional event test 
    - Conditional event must triggered when process is ACTIVE
    - Conditional event must not triggered when process is INACTIVE
- Added timer event test 
    - Timer event must not triggered when process is INACTIVE
- Fixed timer event test (use mock to test is triggered)
    - Timer event must triggered when process is ACTIVE

screenshot

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-660-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-660-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-660-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-660-processmaker.ci.processmaker.net

**Review by caleeli — CHANGES_REQUESTED** [review]
@agustinbusso, Missing Restore button in `Archived Process` tab

https://user-images.githubusercontent.com/8028650/135625308-f453bd3a-ea43-49c7-9580-e64c644d84ed.mp4

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-660-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-660-processmaker.ci.processmaker.net

**Review by caleeli — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://feature-ticket-660-processmaker.ci.processmaker.net

**Pull request merged**
