### PR TITLE
feature/FOUR-9488: IT5 Mobile Participant UX

### PR DESCRIPTION
**Pull request by pmPaulis**
## Issue & Reproduction Steps
This is a feature defined in the document: https://processmaker.atlassian.net/wiki/spaces/PM4/pages/3123380240/Mobile+Participant+UX

## Solution
Implement the following user stories:

- As a mobile participant I want to see what requests I can start directly from my mobile device
- As a mobile participant I want to see my open task list so I can choose to open any of these tasks
- As a mobile participant I want to open a task screen so I can interact with it - review content, fill out input fields, submit

## How to Test

- Login to Processmaker PM4 using the mobile mode

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-9488

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

## Environment Fall
ci:deploy
ci:next

### CODE REVIEW

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-e61f15688b.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-e61f15688b.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-e61f15688b.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-e61f15688b.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-e61f15688b.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-e61f15688b.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-e61f15688b.eng.processmaker.net

**Review by fagubla — APPROVED** [review]

**Review by CarliPinell — APPROVED** [review]

**Pull request merged**
