### PR TITLE
FOUR-3279: Remove Signal by Expression

### PR DESCRIPTION
**Pull request by danloa**
Fixes [https://processmaker.atlassian.net/browse/FOUR-3279](https://processmaker.atlassian.net/browse/FOUR-3279)

### CODE REVIEW

**Review by marcoAntonioNina — APPROVED** [review]

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3279-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3279-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3279-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://bugfix-four-3279-processmaker.ci.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://develop-processmaker.ci.processmaker.net

**Pull request merged**
